// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pFFT_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty_5,
        empty,
        add_i321_i,
        conv3_i_i351_i,
        deltaTheta_sign,
        deltaTheta_isZero,
        deltaTheta_regime,
        deltaTheta_mantissa,
        imagSum_mantissa_write_assign_out,
        imagSum_mantissa_write_assign_out_ap_vld,
        imagSum_exponent_write_assign_out,
        imagSum_exponent_write_assign_out_ap_vld,
        imagSum_regime_write_assign_out,
        imagSum_regime_write_assign_out_ap_vld,
        imagSum_isZero_write_assign_out,
        imagSum_isZero_write_assign_out_ap_vld,
        imagSum_sign_write_assign_out,
        imagSum_sign_write_assign_out_ap_vld,
        realSum_mantissa_write_assign_out,
        realSum_mantissa_write_assign_out_ap_vld,
        realSum_exponent_write_assign_out,
        realSum_exponent_write_assign_out_ap_vld,
        realSum_regime_write_assign_out,
        realSum_regime_write_assign_out_ap_vld,
        realSum_isZero_write_assign_out,
        realSum_isZero_write_assign_out_ap_vld,
        realSum_sign_write_assign_out,
        realSum_sign_write_assign_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] empty_5;
input  [0:0] empty;
input  [6:0] add_i321_i;
input  [29:0] conv3_i_i351_i;
input  [0:0] deltaTheta_sign;
input  [0:0] deltaTheta_isZero;
input  [5:0] deltaTheta_regime;
input  [29:0] deltaTheta_mantissa;
output  [29:0] imagSum_mantissa_write_assign_out;
output   imagSum_mantissa_write_assign_out_ap_vld;
output  [0:0] imagSum_exponent_write_assign_out;
output   imagSum_exponent_write_assign_out_ap_vld;
output  [5:0] imagSum_regime_write_assign_out;
output   imagSum_regime_write_assign_out_ap_vld;
output  [0:0] imagSum_isZero_write_assign_out;
output   imagSum_isZero_write_assign_out_ap_vld;
output  [0:0] imagSum_sign_write_assign_out;
output   imagSum_sign_write_assign_out_ap_vld;
output  [29:0] realSum_mantissa_write_assign_out;
output   realSum_mantissa_write_assign_out_ap_vld;
output  [0:0] realSum_exponent_write_assign_out;
output   realSum_exponent_write_assign_out_ap_vld;
output  [5:0] realSum_regime_write_assign_out;
output   realSum_regime_write_assign_out_ap_vld;
output  [0:0] realSum_isZero_write_assign_out;
output   realSum_isZero_write_assign_out_ap_vld;
output  [0:0] realSum_sign_write_assign_out;
output   realSum_sign_write_assign_out_ap_vld;

reg ap_idle;
reg imagSum_mantissa_write_assign_out_ap_vld;
reg imagSum_exponent_write_assign_out_ap_vld;
reg imagSum_regime_write_assign_out_ap_vld;
reg imagSum_isZero_write_assign_out_ap_vld;
reg imagSum_sign_write_assign_out_ap_vld;
reg realSum_mantissa_write_assign_out_ap_vld;
reg realSum_exponent_write_assign_out_ap_vld;
reg realSum_regime_write_assign_out_ap_vld;
reg realSum_isZero_write_assign_out_ap_vld;
reg realSum_sign_write_assign_out_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln1345_reg_1243;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] angle_exponent_reg_268;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] angle_isZero_reg_280;
reg   [0:0] angle_sign_reg_292;
reg   [0:0] imagSum_exponent_write_assign_reg_304;
reg   [0:0] imagSum_isZero_write_assign_reg_317;
reg   [0:0] imagSum_sign_write_assign_reg_330;
reg   [0:0] realSum_exponent_write_assign_reg_343;
reg   [0:0] realSum_isZero_write_assign_reg_356;
reg   [0:0] realSum_sign_write_assign_reg_369;
wire    ap_block_pp0_stage0_11001;
wire   [59:0] conv3_i_i351_i_cast_fu_494_p1;
reg   [59:0] conv3_i_i351_i_cast_reg_1238;
wire   [0:0] icmp_ln1345_fu_536_p2;
reg   [0:0] icmp_ln1345_reg_1243_pp0_iter1_reg;
reg   [0:0] icmp_ln1345_reg_1243_pp0_iter2_reg;
reg   [0:0] icmp_ln1345_reg_1243_pp0_iter3_reg;
reg   [0:0] icmp_ln1345_reg_1243_pp0_iter4_reg;
reg   [0:0] icmp_ln1345_reg_1243_pp0_iter5_reg;
reg   [0:0] icmp_ln1345_reg_1243_pp0_iter6_reg;
reg   [0:0] icmp_ln1345_reg_1243_pp0_iter7_reg;
reg   [0:0] newret11_reg_1247;
reg   [0:0] newret12_reg_1252;
reg   [0:0] newret14_reg_1257;
reg   [0:0] x_sign_1_reg_1262;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] x_isZero_4_reg_1268;
reg   [5:0] x_regime_4_reg_1274;
reg   [0:0] x_exponent_2_reg_1280;
reg   [29:0] x_mantissa_4_reg_1286;
reg   [0:0] newret2_i_reg_1292;
reg   [0:0] newret4_i_reg_1297;
reg   [5:0] newret6_i_reg_1302;
reg   [29:0] newret8_i_reg_1307;
reg   [0:0] in_sign_reg_1312;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg   [0:0] in_isZero_reg_1318;
reg  signed [5:0] in_regime_reg_1324;
reg   [29:0] in_mantissa_reg_1329;
wire   [0:0] icmp_ln631_fu_623_p2;
reg   [0:0] icmp_ln631_reg_1335;
wire   [5:0] result_regime_19_fu_629_p1;
reg   [5:0] result_regime_19_reg_1340;
reg   [0:0] in_sign_1_reg_1345;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
reg   [0:0] in_sign_1_reg_1345_pp0_iter4_reg;
reg   [0:0] in_isZero_1_reg_1351;
reg   [0:0] in_isZero_1_reg_1351_pp0_iter4_reg;
reg  signed [5:0] in_regime_1_reg_1357;
reg   [29:0] in_mantissa_1_reg_1363;
reg   [29:0] in_mantissa_1_reg_1363_pp0_iter4_reg;
reg   [0:0] in_isZero_2_reg_1369;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
reg   [0:0] in_isZero_2_reg_1369_pp0_iter4_reg;
reg   [0:0] in_isZero_2_reg_1369_pp0_iter5_reg;
reg   [29:0] in_mantissa_2_reg_1374;
reg   [29:0] in_mantissa_2_reg_1374_pp0_iter4_reg;
reg   [29:0] in_mantissa_2_reg_1374_pp0_iter5_reg;
wire   [0:0] icmp_ln631_3_fu_672_p2;
reg   [0:0] icmp_ln631_3_reg_1379;
wire   [5:0] result_regime_25_fu_678_p1;
reg   [5:0] result_regime_25_reg_1384;
wire   [0:0] y_sign_3_fu_682_p2;
reg   [0:0] y_sign_3_reg_1389;
reg   [0:0] y_sign_3_reg_1389_pp0_iter4_reg;
reg   [0:0] y_sign_3_reg_1389_pp0_iter5_reg;
wire   [5:0] result_regime_28_fu_688_p3;
reg   [5:0] result_regime_28_reg_1394;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
reg   [5:0] result_regime_28_reg_1394_pp0_iter4_reg;
reg   [0:0] result_sign_reg_1399;
reg   [0:0] result_isZero_reg_1404;
reg   [5:0] result_regime_reg_1409;
reg   [0:0] result_exponent_reg_1414;
reg   [29:0] result_mantissa_reg_1419;
wire   [5:0] result_regime_23_fu_721_p3;
reg   [5:0] result_regime_23_reg_1424;
reg   [0:0] x_sign_2_reg_1429;
reg   [0:0] x_isZero_5_reg_1434;
reg   [5:0] x_regime_5_reg_1439;
reg   [0:0] x_exponent_3_reg_1444;
reg   [29:0] x_mantissa_5_reg_1449;
wire   [0:0] isZero_fu_759_p2;
reg   [0:0] isZero_reg_1454;
wire   [5:0] regime_13_fu_839_p3;
reg   [5:0] regime_13_reg_1461;
wire   [29:0] mantissa_26_fu_861_p3;
reg   [29:0] mantissa_26_reg_1468;
wire   [0:0] sign_3_fu_875_p2;
reg   [0:0] sign_3_reg_1473;
wire   [0:0] isZero_1_fu_899_p2;
reg   [0:0] isZero_1_reg_1478;
wire   [5:0] regime_16_fu_979_p3;
reg   [5:0] regime_16_reg_1485;
wire   [29:0] mantissa_29_fu_1001_p3;
reg   [29:0] mantissa_29_reg_1492;
wire   [0:0] sign_5_fu_1015_p2;
reg   [0:0] sign_5_reg_1497;
wire   [5:0] regime_22_fu_1050_p3;
reg   [5:0] regime_22_reg_1502;
wire   [5:0] regime_20_fu_1095_p3;
reg   [5:0] regime_20_reg_1507;
wire    ap_block_pp0_stage7_11001;
reg   [0:0] newret6_reg_1512;
reg   [0:0] newret7_reg_1517;
reg   [0:0] newret9_reg_1522;
reg    ap_condition_exit_pp0_iter6_stage7;
wire    grp_positCos_fu_382_ap_start;
wire    grp_positCos_fu_382_ap_done;
wire    grp_positCos_fu_382_ap_idle;
wire    grp_positCos_fu_382_ap_ready;
wire   [0:0] grp_positCos_fu_382_ap_return_0;
wire   [0:0] grp_positCos_fu_382_ap_return_1;
wire   [5:0] grp_positCos_fu_382_ap_return_2;
wire   [0:0] grp_positCos_fu_382_ap_return_3;
wire   [29:0] grp_positCos_fu_382_ap_return_4;
wire    grp_pNAngle_fu_394_ap_start;
wire    grp_pNAngle_fu_394_ap_done;
wire    grp_pNAngle_fu_394_ap_idle;
wire    grp_pNAngle_fu_394_ap_ready;
wire   [0:0] grp_pNAngle_fu_394_ap_return_0;
wire   [0:0] grp_pNAngle_fu_394_ap_return_1;
wire   [5:0] grp_pNAngle_fu_394_ap_return_2;
wire   [0:0] grp_pNAngle_fu_394_ap_return_3;
wire   [29:0] grp_pNAngle_fu_394_ap_return_4;
wire    grp_positAdd_fu_406_ap_start;
wire    grp_positAdd_fu_406_ap_done;
wire    grp_positAdd_fu_406_ap_idle;
wire    grp_positAdd_fu_406_ap_ready;
reg   [0:0] grp_positAdd_fu_406_x_sign;
reg   [0:0] grp_positAdd_fu_406_x_isZero;
reg   [5:0] grp_positAdd_fu_406_x_regime1;
reg   [0:0] grp_positAdd_fu_406_x_exponent2;
reg   [29:0] grp_positAdd_fu_406_x_mantissa3;
reg   [0:0] grp_positAdd_fu_406_y_sign_val;
reg   [0:0] grp_positAdd_fu_406_y_isZero_val;
reg   [5:0] grp_positAdd_fu_406_y_regime1_val;
reg   [29:0] grp_positAdd_fu_406_y_mantissa3_val;
wire   [0:0] grp_positAdd_fu_406_ap_return_0;
wire   [0:0] grp_positAdd_fu_406_ap_return_1;
wire   [5:0] grp_positAdd_fu_406_ap_return_2;
wire   [0:0] grp_positAdd_fu_406_ap_return_3;
wire   [29:0] grp_positAdd_fu_406_ap_return_4;
wire    grp_positMul_fu_430_ap_ready;
reg   [0:0] grp_positMul_fu_430_x_sign;
reg   [0:0] grp_positMul_fu_430_x_isZero;
reg   [5:0] grp_positMul_fu_430_x_regime1;
reg   [0:0] grp_positMul_fu_430_x_exponent2;
reg   [29:0] grp_positMul_fu_430_x_mantissa;
reg   [0:0] grp_positMul_fu_430_y_sign;
reg   [0:0] grp_positMul_fu_430_y_isZero;
reg   [5:0] grp_positMul_fu_430_y_regime1;
reg   [0:0] grp_positMul_fu_430_y_exponent2;
reg   [29:0] grp_positMul_fu_430_y_mantissa3;
wire   [0:0] grp_positMul_fu_430_ap_return_0;
wire   [0:0] grp_positMul_fu_430_ap_return_1;
wire   [5:0] grp_positMul_fu_430_ap_return_2;
wire   [29:0] grp_positMul_fu_430_ap_return_3;
reg   [0:0] ap_phi_mux_angle_exponent_phi_fu_272_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage1;
reg   [0:0] ap_phi_mux_angle_isZero_phi_fu_284_p4;
reg   [0:0] ap_phi_mux_angle_sign_phi_fu_296_p4;
reg   [0:0] ap_phi_mux_imagSum_exponent_write_assign_phi_fu_308_p4;
wire    ap_block_pp0_stage7;
reg   [0:0] ap_phi_mux_imagSum_isZero_write_assign_phi_fu_321_p4;
reg   [0:0] ap_phi_mux_imagSum_sign_write_assign_phi_fu_334_p4;
reg    grp_positCos_fu_382_ap_start_reg;
wire    ap_block_pp0_stage1_ignoreCallOp100;
reg    grp_pNAngle_fu_394_ap_start_reg;
wire    ap_block_pp0_stage1_ignoreCallOp101;
reg    grp_positAdd_fu_406_ap_start_reg;
wire    ap_block_pp0_stage1_ignoreCallOp102;
wire    ap_block_pp0_stage4_ignoreCallOp196;
wire    ap_block_pp0_stage5_ignoreCallOp236;
wire    ap_block_pp0_stage6_ignoreCallOp258;
wire    ap_block_pp0_stage7_ignoreCallOp349;
wire    ap_block_pp0_stage0_ignoreCallOp352;
wire   [0:0] y_sign_1_fu_640_p2;
wire   [5:0] result_regime_27_fu_633_p3;
wire    ap_block_pp0_stage2_ignoreCallOp172;
wire    ap_block_pp0_stage3_ignoreCallOp178;
wire    ap_block_pp0_stage4_ignoreCallOp189;
wire    ap_block_pp0_stage5_ignoreCallOp198;
reg   [5:0] x_regime_fu_122;
reg   [29:0] x_mantissa_fu_126;
reg   [5:0] realSum_regime_write_assign_fu_130;
wire    ap_block_pp0_stage0;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [29:0] realSum_mantissa_write_assign_fu_134;
reg   [5:0] imagSum_regime_write_assign_fu_138;
reg   [29:0] imagSum_mantissa_write_assign_fu_142;
reg   [6:0] n_fu_146;
wire   [6:0] add_ln1345_fu_542_p2;
reg   [6:0] ap_sig_allocacmp_n_1;
wire    ap_block_pp0_stage7_01001;
reg   [29:0] grp_fu_446_p0;
wire   [59:0] zext_ln748_fu_749_p1;
wire   [59:0] zext_ln748_4_fu_889_p1;
wire   [29:0] grp_fu_446_p1;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage2;
wire   [59:0] grp_fu_446_p2;
wire  signed [5:0] sext_ln629_fu_605_p0;
wire  signed [6:0] sext_ln629_fu_605_p1;
wire   [6:0] add_ln629_fu_609_p2;
wire   [1:0] tmp_i_fu_615_p3;
wire  signed [6:0] sext_ln629_3_fu_654_p1;
wire   [6:0] add_ln629_2_fu_658_p2;
wire   [1:0] tmp_5_i_fu_664_p3;
wire  signed [6:0] sext_ln629_2_fu_694_p1;
wire   [6:0] add_ln629_1_fu_697_p2;
wire   [1:0] tmp_i_77_fu_703_p3;
wire   [0:0] icmp_ln631_2_fu_711_p2;
wire   [5:0] result_regime_22_fu_717_p1;
wire  signed [6:0] sext_ln756_fu_764_p1;
wire   [6:0] zext_ln756_fu_768_p1;
wire   [6:0] add_ln757_fu_772_p2;
wire   [6:0] sf_r_fu_778_p2;
wire   [1:0] tmp_fu_787_p3;
wire   [5:0] trunc_ln734_fu_783_p1;
wire   [0:0] grp_fu_486_p3;
wire   [5:0] sf_r_14_fu_801_p2;
wire   [29:0] mantissa_fu_807_p3;
wire   [29:0] mantissa_25_fu_815_p3;
wire   [0:0] icmp_ln771_fu_795_p2;
wire   [5:0] sf_r_19_fu_823_p3;
wire   [0:0] or_ln820_7_fu_855_p2;
wire   [29:0] select_ln820_12_fu_847_p3;
wire   [29:0] mantissa_13_fu_831_p3;
wire   [0:0] sign_fu_754_p2;
wire   [0:0] xor_ln820_fu_869_p2;
wire  signed [6:0] sext_ln756_1_fu_904_p1;
wire   [6:0] add_ln757_4_fu_912_p2;
wire   [6:0] zext_ln756_1_fu_908_p1;
wire   [6:0] sf_r_16_fu_917_p2;
wire   [1:0] tmp_s_fu_927_p3;
wire   [5:0] trunc_ln734_2_fu_923_p1;
wire   [5:0] sf_r_17_fu_941_p2;
wire   [29:0] mantissa_27_fu_947_p3;
wire   [29:0] mantissa_28_fu_955_p3;
wire   [0:0] icmp_ln771_1_fu_935_p2;
wire   [5:0] sf_r_20_fu_963_p3;
wire   [0:0] or_ln820_8_fu_995_p2;
wire   [29:0] select_ln820_16_fu_987_p3;
wire   [29:0] mantissa_18_fu_971_p3;
wire   [0:0] sign_4_fu_894_p2;
wire   [0:0] xor_ln820_1_fu_1009_p2;
wire   [0:0] icmp_ln804_1_fu_1026_p2;
wire   [0:0] icmp_ln803_1_fu_1021_p2;
wire   [0:0] or_ln820_2_fu_1045_p2;
wire   [5:0] select_ln820_14_fu_1038_p3;
wire   [5:0] select_ln804_1_fu_1031_p3;
wire   [0:0] icmp_ln804_fu_1071_p2;
wire   [0:0] icmp_ln803_fu_1066_p2;
wire   [0:0] or_ln820_fu_1090_p2;
wire   [5:0] select_ln820_fu_1083_p3;
wire   [5:0] select_ln804_fu_1076_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0_1to7;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_positCos_fu_382_ap_start_reg = 1'b0;
#0 grp_pNAngle_fu_394_ap_start_reg = 1'b0;
#0 grp_positAdd_fu_406_ap_start_reg = 1'b0;
#0 x_regime_fu_122 = 6'd0;
#0 x_mantissa_fu_126 = 30'd0;
#0 realSum_regime_write_assign_fu_130 = 6'd0;
#0 realSum_mantissa_write_assign_fu_134 = 30'd0;
#0 imagSum_regime_write_assign_fu_138 = 6'd0;
#0 imagSum_mantissa_write_assign_fu_142 = 30'd0;
#0 n_fu_146 = 7'd0;
#0 ap_done_reg = 1'b0;
end

pFFT_positCos grp_positCos_fu_382(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_positCos_fu_382_ap_start),
    .ap_done(grp_positCos_fu_382_ap_done),
    .ap_idle(grp_positCos_fu_382_ap_idle),
    .ap_ready(grp_positCos_fu_382_ap_ready),
    .x_sign(ap_phi_mux_angle_sign_phi_fu_296_p4),
    .x_isZero(ap_phi_mux_angle_isZero_phi_fu_284_p4),
    .x_regime(x_regime_fu_122),
    .x_exponent(ap_phi_mux_angle_exponent_phi_fu_272_p4),
    .x_mantissa(x_mantissa_fu_126),
    .ap_return_0(grp_positCos_fu_382_ap_return_0),
    .ap_return_1(grp_positCos_fu_382_ap_return_1),
    .ap_return_2(grp_positCos_fu_382_ap_return_2),
    .ap_return_3(grp_positCos_fu_382_ap_return_3),
    .ap_return_4(grp_positCos_fu_382_ap_return_4)
);

pFFT_pNAngle grp_pNAngle_fu_394(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pNAngle_fu_394_ap_start),
    .ap_done(grp_pNAngle_fu_394_ap_done),
    .ap_idle(grp_pNAngle_fu_394_ap_idle),
    .ap_ready(grp_pNAngle_fu_394_ap_ready),
    .x_sign(ap_phi_mux_angle_sign_phi_fu_296_p4),
    .x_isZero(ap_phi_mux_angle_isZero_phi_fu_284_p4),
    .x_regime(x_regime_fu_122),
    .x_exponent(ap_phi_mux_angle_exponent_phi_fu_272_p4),
    .x_mantissa(x_mantissa_fu_126),
    .ap_return_0(grp_pNAngle_fu_394_ap_return_0),
    .ap_return_1(grp_pNAngle_fu_394_ap_return_1),
    .ap_return_2(grp_pNAngle_fu_394_ap_return_2),
    .ap_return_3(grp_pNAngle_fu_394_ap_return_3),
    .ap_return_4(grp_pNAngle_fu_394_ap_return_4)
);

pFFT_positAdd grp_positAdd_fu_406(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_positAdd_fu_406_ap_start),
    .ap_done(grp_positAdd_fu_406_ap_done),
    .ap_idle(grp_positAdd_fu_406_ap_idle),
    .ap_ready(grp_positAdd_fu_406_ap_ready),
    .ap_ce(1'b1),
    .x_sign(grp_positAdd_fu_406_x_sign),
    .x_isZero(grp_positAdd_fu_406_x_isZero),
    .x_regime1(grp_positAdd_fu_406_x_regime1),
    .x_exponent2(grp_positAdd_fu_406_x_exponent2),
    .x_mantissa3(grp_positAdd_fu_406_x_mantissa3),
    .y_sign_val(grp_positAdd_fu_406_y_sign_val),
    .y_isZero_val(grp_positAdd_fu_406_y_isZero_val),
    .y_regime1_val(grp_positAdd_fu_406_y_regime1_val),
    .y_exponent2_val(1'd0),
    .y_mantissa3_val(grp_positAdd_fu_406_y_mantissa3_val),
    .ap_return_0(grp_positAdd_fu_406_ap_return_0),
    .ap_return_1(grp_positAdd_fu_406_ap_return_1),
    .ap_return_2(grp_positAdd_fu_406_ap_return_2),
    .ap_return_3(grp_positAdd_fu_406_ap_return_3),
    .ap_return_4(grp_positAdd_fu_406_ap_return_4)
);

pFFT_positMul grp_positMul_fu_430(
    .ap_ready(grp_positMul_fu_430_ap_ready),
    .x_sign(grp_positMul_fu_430_x_sign),
    .x_isZero(grp_positMul_fu_430_x_isZero),
    .x_regime1(grp_positMul_fu_430_x_regime1),
    .x_exponent2(grp_positMul_fu_430_x_exponent2),
    .x_mantissa(grp_positMul_fu_430_x_mantissa),
    .y_sign(grp_positMul_fu_430_y_sign),
    .y_isZero(grp_positMul_fu_430_y_isZero),
    .y_regime1(grp_positMul_fu_430_y_regime1),
    .y_exponent2(grp_positMul_fu_430_y_exponent2),
    .y_mantissa3(grp_positMul_fu_430_y_mantissa3),
    .ap_return_0(grp_positMul_fu_430_ap_return_0),
    .ap_return_1(grp_positMul_fu_430_ap_return_1),
    .ap_return_2(grp_positMul_fu_430_ap_return_2),
    .ap_return_3(grp_positMul_fu_430_ap_return_3),
    .ap_rst(ap_rst)
);

pFFT_mul_30ns_30ns_60_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 60 ))
mul_30ns_30ns_60_1_1_U116(
    .din0(grp_fu_446_p0),
    .din1(grp_fu_446_p1),
    .dout(grp_fu_446_p2)
);

pFFT_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter6_stage7)) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pNAngle_fu_394_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1345_fu_536_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_pNAngle_fu_394_ap_start_reg <= 1'b1;
        end else if ((grp_pNAngle_fu_394_ap_ready == 1'b1)) begin
            grp_pNAngle_fu_394_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_positAdd_fu_406_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1345_fu_536_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            grp_positAdd_fu_406_ap_start_reg <= 1'b1;
        end else if ((grp_positAdd_fu_406_ap_ready == 1'b1)) begin
            grp_positAdd_fu_406_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_positCos_fu_382_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1345_fu_536_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_positCos_fu_382_ap_start_reg <= 1'b1;
        end else if ((grp_positCos_fu_382_ap_ready == 1'b1)) begin
            grp_positCos_fu_382_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        angle_exponent_reg_268 <= newret14_reg_1257;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        angle_exponent_reg_268 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        angle_isZero_reg_280 <= newret12_reg_1252;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        angle_isZero_reg_280 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        angle_sign_reg_292 <= newret11_reg_1247;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        angle_sign_reg_292 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_exponent_write_assign_reg_304 <= newret9_reg_1522;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imagSum_exponent_write_assign_reg_304 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_isZero_write_assign_reg_317 <= newret7_reg_1517;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imagSum_isZero_write_assign_reg_317 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imagSum_mantissa_write_assign_fu_142 <= 30'd536870912;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        imagSum_mantissa_write_assign_fu_142 <= grp_positAdd_fu_406_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imagSum_regime_write_assign_fu_138 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        imagSum_regime_write_assign_fu_138 <= grp_positAdd_fu_406_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_sign_write_assign_reg_330 <= newret6_reg_1512;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imagSum_sign_write_assign_reg_330 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln1345_fu_536_p2 == 1'd0))) begin
            n_fu_146 <= add_ln1345_fu_542_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_146 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_exponent_write_assign_reg_343 <= grp_positAdd_fu_406_ap_return_3;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        realSum_exponent_write_assign_reg_343 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_isZero_write_assign_reg_356 <= grp_positAdd_fu_406_ap_return_1;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        realSum_isZero_write_assign_reg_356 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        realSum_mantissa_write_assign_fu_134 <= 30'd536870912;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_mantissa_write_assign_fu_134 <= grp_positAdd_fu_406_ap_return_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        realSum_regime_write_assign_fu_130 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_regime_write_assign_fu_130 <= grp_positAdd_fu_406_ap_return_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_sign_write_assign_reg_369 <= grp_positAdd_fu_406_ap_return_0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        realSum_sign_write_assign_reg_369 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_mantissa_fu_126 <= 30'd0;
        end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_mantissa_fu_126 <= grp_positAdd_fu_406_ap_return_4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_regime_fu_122 <= 6'd0;
        end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_regime_fu_122 <= grp_positAdd_fu_406_ap_return_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        regime_20_reg_1507 <= regime_20_fu_1095_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv3_i_i351_i_cast_reg_1238[29 : 0] <= conv3_i_i351_i_cast_fu_494_p1[29 : 0];
        icmp_ln1345_reg_1243 <= icmp_ln1345_fu_536_p2;
        icmp_ln1345_reg_1243_pp0_iter1_reg <= icmp_ln1345_reg_1243;
        icmp_ln1345_reg_1243_pp0_iter2_reg <= icmp_ln1345_reg_1243_pp0_iter1_reg;
        icmp_ln1345_reg_1243_pp0_iter3_reg <= icmp_ln1345_reg_1243_pp0_iter2_reg;
        icmp_ln1345_reg_1243_pp0_iter4_reg <= icmp_ln1345_reg_1243_pp0_iter3_reg;
        icmp_ln1345_reg_1243_pp0_iter5_reg <= icmp_ln1345_reg_1243_pp0_iter4_reg;
        icmp_ln1345_reg_1243_pp0_iter6_reg <= icmp_ln1345_reg_1243_pp0_iter5_reg;
        icmp_ln1345_reg_1243_pp0_iter7_reg <= icmp_ln1345_reg_1243_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        icmp_ln631_3_reg_1379 <= icmp_ln631_3_fu_672_p2;
        in_isZero_2_reg_1369_pp0_iter4_reg <= in_isZero_2_reg_1369;
        in_isZero_2_reg_1369_pp0_iter5_reg <= in_isZero_2_reg_1369_pp0_iter4_reg;
        in_mantissa_2_reg_1374_pp0_iter4_reg <= in_mantissa_2_reg_1374;
        in_mantissa_2_reg_1374_pp0_iter5_reg <= in_mantissa_2_reg_1374_pp0_iter4_reg;
        isZero_1_reg_1478 <= isZero_1_fu_899_p2;
        mantissa_29_reg_1492 <= mantissa_29_fu_1001_p3;
        regime_16_reg_1485 <= regime_16_fu_979_p3;
        result_regime_25_reg_1384 <= result_regime_25_fu_678_p1;
        sign_5_reg_1497 <= sign_5_fu_1015_p2;
        y_sign_3_reg_1389 <= y_sign_3_fu_682_p2;
        y_sign_3_reg_1389_pp0_iter4_reg <= y_sign_3_reg_1389;
        y_sign_3_reg_1389_pp0_iter5_reg <= y_sign_3_reg_1389_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        icmp_ln631_reg_1335 <= icmp_ln631_fu_623_p2;
        result_regime_19_reg_1340 <= result_regime_19_fu_629_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        in_isZero_1_reg_1351 <= grp_positMul_fu_430_ap_return_1;
        in_mantissa_1_reg_1363 <= grp_positMul_fu_430_ap_return_3;
        in_regime_1_reg_1357 <= grp_positMul_fu_430_ap_return_2;
        in_sign_1_reg_1345 <= grp_positMul_fu_430_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        in_isZero_1_reg_1351_pp0_iter4_reg <= in_isZero_1_reg_1351;
        in_mantissa_1_reg_1363_pp0_iter4_reg <= in_mantissa_1_reg_1363;
        in_sign_1_reg_1345_pp0_iter4_reg <= in_sign_1_reg_1345;
        isZero_reg_1454 <= isZero_fu_759_p2;
        mantissa_26_reg_1468 <= mantissa_26_fu_861_p3;
        regime_13_reg_1461 <= regime_13_fu_839_p3;
        result_regime_23_reg_1424 <= result_regime_23_fu_721_p3;
        sign_3_reg_1473 <= sign_3_fu_875_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        in_isZero_2_reg_1369 <= grp_positMul_fu_430_ap_return_1;
        in_mantissa_2_reg_1374 <= grp_positMul_fu_430_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        in_isZero_reg_1318 <= grp_positMul_fu_430_ap_return_1;
        in_mantissa_reg_1329 <= grp_positMul_fu_430_ap_return_3;
        in_regime_reg_1324 <= grp_positMul_fu_430_ap_return_2;
        in_sign_reg_1312 <= grp_positMul_fu_430_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        newret11_reg_1247 <= grp_positAdd_fu_406_ap_return_0;
        newret12_reg_1252 <= grp_positAdd_fu_406_ap_return_1;
        newret14_reg_1257 <= grp_positAdd_fu_406_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        newret2_i_reg_1292 <= grp_positMul_fu_430_ap_return_0;
        newret4_i_reg_1297 <= grp_positMul_fu_430_ap_return_1;
        newret6_i_reg_1302 <= grp_positMul_fu_430_ap_return_2;
        newret8_i_reg_1307 <= grp_positMul_fu_430_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        newret6_reg_1512 <= grp_positAdd_fu_406_ap_return_0;
        newret7_reg_1517 <= grp_positAdd_fu_406_ap_return_1;
        newret9_reg_1522 <= grp_positAdd_fu_406_ap_return_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        regime_22_reg_1502 <= regime_22_fu_1050_p3;
        result_regime_28_reg_1394 <= result_regime_28_fu_688_p3;
        result_regime_28_reg_1394_pp0_iter4_reg <= result_regime_28_reg_1394;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        result_exponent_reg_1414 <= grp_positAdd_fu_406_ap_return_3;
        result_isZero_reg_1404 <= grp_positAdd_fu_406_ap_return_1;
        result_mantissa_reg_1419 <= grp_positAdd_fu_406_ap_return_4;
        result_regime_reg_1409 <= grp_positAdd_fu_406_ap_return_2;
        result_sign_reg_1399 <= grp_positAdd_fu_406_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        x_exponent_2_reg_1280 <= grp_pNAngle_fu_394_ap_return_3;
        x_isZero_4_reg_1268 <= grp_pNAngle_fu_394_ap_return_1;
        x_mantissa_4_reg_1286 <= grp_pNAngle_fu_394_ap_return_4;
        x_regime_4_reg_1274 <= grp_pNAngle_fu_394_ap_return_2;
        x_sign_1_reg_1262 <= grp_pNAngle_fu_394_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        x_exponent_3_reg_1444 <= grp_positAdd_fu_406_ap_return_3;
        x_isZero_5_reg_1434 <= grp_positAdd_fu_406_ap_return_1;
        x_mantissa_5_reg_1449 <= grp_positAdd_fu_406_ap_return_4;
        x_regime_5_reg_1439 <= grp_positAdd_fu_406_ap_return_2;
        x_sign_2_reg_1429 <= grp_positAdd_fu_406_ap_return_0;
    end
end

always @ (*) begin
    if (((icmp_ln1345_reg_1243 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter6_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter6_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to7 = 1'b1;
    end else begin
        ap_idle_pp0_1to7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_mux_angle_exponent_phi_fu_272_p4 = newret14_reg_1257;
    end else begin
        ap_phi_mux_angle_exponent_phi_fu_272_p4 = angle_exponent_reg_268;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_mux_angle_isZero_phi_fu_284_p4 = newret12_reg_1252;
    end else begin
        ap_phi_mux_angle_isZero_phi_fu_284_p4 = angle_isZero_reg_280;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_mux_angle_sign_phi_fu_296_p4 = newret11_reg_1247;
    end else begin
        ap_phi_mux_angle_sign_phi_fu_296_p4 = angle_sign_reg_292;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_mux_imagSum_exponent_write_assign_phi_fu_308_p4 = newret9_reg_1522;
    end else begin
        ap_phi_mux_imagSum_exponent_write_assign_phi_fu_308_p4 = imagSum_exponent_write_assign_reg_304;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_mux_imagSum_isZero_write_assign_phi_fu_321_p4 = newret7_reg_1517;
    end else begin
        ap_phi_mux_imagSum_isZero_write_assign_phi_fu_321_p4 = imagSum_isZero_write_assign_reg_317;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter7_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_mux_imagSum_sign_write_assign_phi_fu_334_p4 = newret6_reg_1512;
    end else begin
        ap_phi_mux_imagSum_sign_write_assign_phi_fu_334_p4 = imagSum_sign_write_assign_reg_330;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_n_1 = n_fu_146;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_fu_446_p0 = zext_ln748_4_fu_889_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_446_p0 = zext_ln748_fu_749_p1;
        end else begin
            grp_fu_446_p0 = 'bx;
        end
    end else begin
        grp_fu_446_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_x_exponent2 = realSum_exponent_write_assign_reg_343;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_x_exponent2 = ap_phi_mux_imagSum_exponent_write_assign_phi_fu_308_p4;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_x_exponent2 = x_exponent_3_reg_1444;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_x_exponent2 = result_exponent_reg_1414;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_x_exponent2 = x_exponent_2_reg_1280;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_x_exponent2 = ap_phi_mux_angle_exponent_phi_fu_272_p4;
    end else begin
        grp_positAdd_fu_406_x_exponent2 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_x_isZero = realSum_isZero_write_assign_reg_356;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_x_isZero = ap_phi_mux_imagSum_isZero_write_assign_phi_fu_321_p4;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_x_isZero = x_isZero_5_reg_1434;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_x_isZero = result_isZero_reg_1404;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_x_isZero = x_isZero_4_reg_1268;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_x_isZero = ap_phi_mux_angle_isZero_phi_fu_284_p4;
    end else begin
        grp_positAdd_fu_406_x_isZero = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_x_mantissa3 = realSum_mantissa_write_assign_fu_134;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_x_mantissa3 = imagSum_mantissa_write_assign_fu_142;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_x_mantissa3 = x_mantissa_5_reg_1449;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_x_mantissa3 = result_mantissa_reg_1419;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_x_mantissa3 = x_mantissa_4_reg_1286;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_x_mantissa3 = x_mantissa_fu_126;
    end else begin
        grp_positAdd_fu_406_x_mantissa3 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_x_regime1 = realSum_regime_write_assign_fu_130;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_x_regime1 = imagSum_regime_write_assign_fu_138;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_x_regime1 = x_regime_5_reg_1439;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_x_regime1 = result_regime_reg_1409;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_x_regime1 = x_regime_4_reg_1274;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_x_regime1 = x_regime_fu_122;
    end else begin
        grp_positAdd_fu_406_x_regime1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_x_sign = realSum_sign_write_assign_reg_369;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_x_sign = ap_phi_mux_imagSum_sign_write_assign_phi_fu_334_p4;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_x_sign = x_sign_2_reg_1429;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_x_sign = result_sign_reg_1399;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_x_sign = x_sign_1_reg_1262;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_x_sign = ap_phi_mux_angle_sign_phi_fu_296_p4;
    end else begin
        grp_positAdd_fu_406_x_sign = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_y_isZero_val = isZero_reg_1454;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_y_isZero_val = isZero_1_reg_1478;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_y_isZero_val = in_isZero_2_reg_1369_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_y_isZero_val = in_isZero_1_reg_1351_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_y_isZero_val = in_isZero_reg_1318;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_y_isZero_val = deltaTheta_isZero;
    end else begin
        grp_positAdd_fu_406_y_isZero_val = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_y_mantissa3_val = mantissa_26_reg_1468;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_y_mantissa3_val = mantissa_29_reg_1492;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_y_mantissa3_val = in_mantissa_2_reg_1374_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_y_mantissa3_val = in_mantissa_1_reg_1363_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_y_mantissa3_val = in_mantissa_reg_1329;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_y_mantissa3_val = deltaTheta_mantissa;
    end else begin
        grp_positAdd_fu_406_y_mantissa3_val = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_y_regime1_val = regime_20_reg_1507;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_y_regime1_val = regime_22_reg_1502;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_y_regime1_val = result_regime_28_reg_1394_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_y_regime1_val = result_regime_23_reg_1424;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_y_regime1_val = result_regime_27_fu_633_p3;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_y_regime1_val = deltaTheta_regime;
    end else begin
        grp_positAdd_fu_406_y_regime1_val = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_ignoreCallOp352) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_positAdd_fu_406_y_sign_val = sign_3_reg_1473;
    end else if (((1'b0 == ap_block_pp0_stage7_ignoreCallOp349) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_positAdd_fu_406_y_sign_val = sign_5_reg_1497;
    end else if (((1'b0 == ap_block_pp0_stage6_ignoreCallOp258) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_positAdd_fu_406_y_sign_val = y_sign_3_reg_1389_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp236) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_positAdd_fu_406_y_sign_val = in_sign_1_reg_1345_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp196) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_positAdd_fu_406_y_sign_val = y_sign_1_fu_640_p2;
    end else if (((icmp_ln1345_reg_1243 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_ignoreCallOp102) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_positAdd_fu_406_y_sign_val = deltaTheta_sign;
    end else begin
        grp_positAdd_fu_406_y_sign_val = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_positMul_fu_430_x_exponent2 = 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_positMul_fu_430_x_exponent2 = grp_pNAngle_fu_394_ap_return_3;
    end else begin
        grp_positMul_fu_430_x_exponent2 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_positMul_fu_430_x_isZero = newret4_i_reg_1297;
    end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_positMul_fu_430_x_isZero = grp_pNAngle_fu_394_ap_return_1;
    end else begin
        grp_positMul_fu_430_x_isZero = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_positMul_fu_430_x_mantissa = newret8_i_reg_1307;
    end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_positMul_fu_430_x_mantissa = grp_pNAngle_fu_394_ap_return_4;
    end else begin
        grp_positMul_fu_430_x_mantissa = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_positMul_fu_430_x_regime1 = newret6_i_reg_1302;
    end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_positMul_fu_430_x_regime1 = grp_pNAngle_fu_394_ap_return_2;
    end else begin
        grp_positMul_fu_430_x_regime1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_positMul_fu_430_x_sign = newret2_i_reg_1292;
    end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_positMul_fu_430_x_sign = grp_pNAngle_fu_394_ap_return_0;
    end else begin
        grp_positMul_fu_430_x_sign = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_positMul_fu_430_y_exponent2 = 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_positMul_fu_430_y_exponent2 = x_exponent_2_reg_1280;
    end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_positMul_fu_430_y_exponent2 = grp_pNAngle_fu_394_ap_return_3;
    end else begin
        grp_positMul_fu_430_y_exponent2 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0))) begin
        if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_positMul_fu_430_y_isZero = in_isZero_1_reg_1351;
        end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_positMul_fu_430_y_isZero = in_isZero_reg_1318;
        end else if (((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_positMul_fu_430_y_isZero = x_isZero_4_reg_1268;
        end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_positMul_fu_430_y_isZero = grp_pNAngle_fu_394_ap_return_1;
        end else begin
            grp_positMul_fu_430_y_isZero = 'bx;
        end
    end else begin
        grp_positMul_fu_430_y_isZero = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0))) begin
        if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_positMul_fu_430_y_mantissa3 = in_mantissa_1_reg_1363;
        end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_positMul_fu_430_y_mantissa3 = in_mantissa_reg_1329;
        end else if (((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_positMul_fu_430_y_mantissa3 = x_mantissa_4_reg_1286;
        end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_positMul_fu_430_y_mantissa3 = grp_pNAngle_fu_394_ap_return_4;
        end else begin
            grp_positMul_fu_430_y_mantissa3 = 'bx;
        end
    end else begin
        grp_positMul_fu_430_y_mantissa3 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0))) begin
        if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_positMul_fu_430_y_regime1 = in_regime_1_reg_1357;
        end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_positMul_fu_430_y_regime1 = in_regime_reg_1324;
        end else if (((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_positMul_fu_430_y_regime1 = x_regime_4_reg_1274;
        end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_positMul_fu_430_y_regime1 = grp_pNAngle_fu_394_ap_return_2;
        end else begin
            grp_positMul_fu_430_y_regime1 = 'bx;
        end
    end else begin
        grp_positMul_fu_430_y_regime1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln1345_reg_1243_pp0_iter3_reg == 1'd0))) begin
        if (((1'b0 == ap_block_pp0_stage5_ignoreCallOp198) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_positMul_fu_430_y_sign = in_sign_1_reg_1345;
        end else if (((1'b0 == ap_block_pp0_stage4_ignoreCallOp189) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_positMul_fu_430_y_sign = in_sign_reg_1312;
        end else if (((1'b0 == ap_block_pp0_stage3_ignoreCallOp178) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_positMul_fu_430_y_sign = x_sign_1_reg_1262;
        end else if (((1'b0 == ap_block_pp0_stage2_ignoreCallOp172) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_positMul_fu_430_y_sign = grp_pNAngle_fu_394_ap_return_0;
        end else begin
            grp_positMul_fu_430_y_sign = 'bx;
        end
    end else begin
        grp_positMul_fu_430_y_sign = 'bx;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_exponent_write_assign_out_ap_vld = 1'b1;
    end else begin
        imagSum_exponent_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_isZero_write_assign_out_ap_vld = 1'b1;
    end else begin
        imagSum_isZero_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_mantissa_write_assign_out_ap_vld = 1'b1;
    end else begin
        imagSum_mantissa_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_regime_write_assign_out_ap_vld = 1'b1;
    end else begin
        imagSum_regime_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        imagSum_sign_write_assign_out_ap_vld = 1'b1;
    end else begin
        imagSum_sign_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_exponent_write_assign_out_ap_vld = 1'b1;
    end else begin
        realSum_exponent_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_isZero_write_assign_out_ap_vld = 1'b1;
    end else begin
        realSum_isZero_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_mantissa_write_assign_out_ap_vld = 1'b1;
    end else begin
        realSum_mantissa_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_regime_write_assign_out_ap_vld = 1'b1;
    end else begin
        realSum_regime_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (icmp_ln1345_reg_1243_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        realSum_sign_write_assign_out_ap_vld = 1'b1;
    end else begin
        realSum_sign_write_assign_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to7 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1345_fu_542_p2 = (ap_sig_allocacmp_n_1 + 7'd1);

assign add_ln629_1_fu_697_p2 = ($signed(sext_ln629_2_fu_694_p1) + $signed(7'd121));

assign add_ln629_2_fu_658_p2 = ($signed(sext_ln629_3_fu_654_p1) + $signed(7'd116));

assign add_ln629_fu_609_p2 = ($signed(sext_ln629_fu_605_p1) + $signed(7'd125));

assign add_ln757_4_fu_912_p2 = ($signed(sext_ln756_1_fu_904_p1) + $signed(add_i321_i));

assign add_ln757_fu_772_p2 = ($signed(sext_ln756_fu_764_p1) + $signed(zext_ln756_fu_768_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp352 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp100 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp101 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_ignoreCallOp102 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_ignoreCallOp172 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_ignoreCallOp178 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_ignoreCallOp189 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_ignoreCallOp196 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_ignoreCallOp198 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_ignoreCallOp236 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_ignoreCallOp258 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_ignoreCallOp349 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_ready = ap_ready_sig;

assign conv3_i_i351_i_cast_fu_494_p1 = conv3_i_i351_i;

assign grp_fu_446_p1 = conv3_i_i351_i_cast_reg_1238;

assign grp_fu_486_p3 = grp_fu_446_p2[32'd59];

assign grp_pNAngle_fu_394_ap_start = grp_pNAngle_fu_394_ap_start_reg;

assign grp_positAdd_fu_406_ap_start = grp_positAdd_fu_406_ap_start_reg;

assign grp_positCos_fu_382_ap_start = grp_positCos_fu_382_ap_start_reg;

assign icmp_ln1345_fu_536_p2 = ((ap_sig_allocacmp_n_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln631_2_fu_711_p2 = ((tmp_i_77_fu_703_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln631_3_fu_672_p2 = ((tmp_5_i_fu_664_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln631_fu_623_p2 = ((tmp_i_fu_615_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln771_1_fu_935_p2 = ((tmp_s_fu_927_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln771_fu_795_p2 = ((tmp_fu_787_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln803_1_fu_1021_p2 = (($signed(regime_16_reg_1485) > $signed(6'd29)) ? 1'b1 : 1'b0);

assign icmp_ln803_fu_1066_p2 = (($signed(regime_13_reg_1461) > $signed(6'd29)) ? 1'b1 : 1'b0);

assign icmp_ln804_1_fu_1026_p2 = (($signed(regime_16_reg_1485) > $signed(6'd34)) ? 1'b1 : 1'b0);

assign icmp_ln804_fu_1071_p2 = (($signed(regime_13_reg_1461) > $signed(6'd34)) ? 1'b1 : 1'b0);

assign imagSum_exponent_write_assign_out = imagSum_exponent_write_assign_reg_304;

assign imagSum_isZero_write_assign_out = imagSum_isZero_write_assign_reg_317;

assign imagSum_mantissa_write_assign_out = imagSum_mantissa_write_assign_fu_142;

assign imagSum_regime_write_assign_out = imagSum_regime_write_assign_fu_138;

assign imagSum_sign_write_assign_out = imagSum_sign_write_assign_reg_330;

assign isZero_1_fu_899_p2 = (grp_positAdd_fu_406_ap_return_1 | empty);

assign isZero_fu_759_p2 = (grp_positCos_fu_382_ap_return_1 | empty);

assign mantissa_13_fu_831_p3 = ((grp_fu_486_p3[0:0] == 1'b1) ? mantissa_fu_807_p3 : mantissa_25_fu_815_p3);

assign mantissa_18_fu_971_p3 = ((grp_fu_486_p3[0:0] == 1'b1) ? mantissa_27_fu_947_p3 : mantissa_28_fu_955_p3);

assign mantissa_25_fu_815_p3 = {{grp_fu_446_p2[58:29]}};

assign mantissa_26_fu_861_p3 = ((or_ln820_7_fu_855_p2[0:0] == 1'b1) ? select_ln820_12_fu_847_p3 : mantissa_13_fu_831_p3);

assign mantissa_27_fu_947_p3 = {{grp_fu_446_p2[59:30]}};

assign mantissa_28_fu_955_p3 = {{grp_fu_446_p2[58:29]}};

assign mantissa_29_fu_1001_p3 = ((or_ln820_8_fu_995_p2[0:0] == 1'b1) ? select_ln820_16_fu_987_p3 : mantissa_18_fu_971_p3);

assign mantissa_fu_807_p3 = {{grp_fu_446_p2[59:30]}};

assign or_ln820_2_fu_1045_p2 = (isZero_1_reg_1478 | icmp_ln803_1_fu_1021_p2);

assign or_ln820_7_fu_855_p2 = (isZero_fu_759_p2 | icmp_ln771_fu_795_p2);

assign or_ln820_8_fu_995_p2 = (isZero_1_fu_899_p2 | icmp_ln771_1_fu_935_p2);

assign or_ln820_fu_1090_p2 = (isZero_reg_1454 | icmp_ln803_fu_1066_p2);

assign realSum_exponent_write_assign_out = realSum_exponent_write_assign_reg_343;

assign realSum_isZero_write_assign_out = realSum_isZero_write_assign_reg_356;

assign realSum_mantissa_write_assign_out = realSum_mantissa_write_assign_fu_134;

assign realSum_regime_write_assign_out = realSum_regime_write_assign_fu_130;

assign realSum_sign_write_assign_out = realSum_sign_write_assign_reg_369;

assign regime_13_fu_839_p3 = ((icmp_ln771_fu_795_p2[0:0] == 1'b1) ? 6'd34 : sf_r_19_fu_823_p3);

assign regime_16_fu_979_p3 = ((icmp_ln771_1_fu_935_p2[0:0] == 1'b1) ? 6'd34 : sf_r_20_fu_963_p3);

assign regime_20_fu_1095_p3 = ((or_ln820_fu_1090_p2[0:0] == 1'b1) ? select_ln820_fu_1083_p3 : select_ln804_fu_1076_p3);

assign regime_22_fu_1050_p3 = ((or_ln820_2_fu_1045_p2[0:0] == 1'b1) ? select_ln820_14_fu_1038_p3 : select_ln804_1_fu_1031_p3);

assign result_regime_19_fu_629_p1 = add_ln629_fu_609_p2[5:0];

assign result_regime_22_fu_717_p1 = add_ln629_1_fu_697_p2[5:0];

assign result_regime_23_fu_721_p3 = ((icmp_ln631_2_fu_711_p2[0:0] == 1'b1) ? 6'd34 : result_regime_22_fu_717_p1);

assign result_regime_25_fu_678_p1 = add_ln629_2_fu_658_p2[5:0];

assign result_regime_27_fu_633_p3 = ((icmp_ln631_reg_1335[0:0] == 1'b1) ? 6'd34 : result_regime_19_reg_1340);

assign result_regime_28_fu_688_p3 = ((icmp_ln631_3_reg_1379[0:0] == 1'b1) ? 6'd34 : result_regime_25_reg_1384);

assign select_ln804_1_fu_1031_p3 = ((icmp_ln804_1_fu_1026_p2[0:0] == 1'b1) ? regime_16_reg_1485 : 6'd34);

assign select_ln804_fu_1076_p3 = ((icmp_ln804_fu_1071_p2[0:0] == 1'b1) ? regime_13_reg_1461 : 6'd34);

assign select_ln820_12_fu_847_p3 = ((isZero_fu_759_p2[0:0] == 1'b1) ? 30'd0 : 30'd536870912);

assign select_ln820_14_fu_1038_p3 = ((isZero_1_reg_1478[0:0] == 1'b1) ? 6'd0 : 6'd30);

assign select_ln820_16_fu_987_p3 = ((isZero_1_fu_899_p2[0:0] == 1'b1) ? 30'd0 : 30'd536870912);

assign select_ln820_fu_1083_p3 = ((isZero_reg_1454[0:0] == 1'b1) ? 6'd0 : 6'd30);

assign sext_ln629_2_fu_694_p1 = in_regime_1_reg_1357;

assign sext_ln629_3_fu_654_p1 = $signed(grp_positMul_fu_430_ap_return_2);

assign sext_ln629_fu_605_p0 = grp_positMul_fu_430_ap_return_2;

assign sext_ln629_fu_605_p1 = sext_ln629_fu_605_p0;

assign sext_ln756_1_fu_904_p1 = $signed(grp_positAdd_fu_406_ap_return_2);

assign sext_ln756_fu_764_p1 = $signed(grp_positCos_fu_382_ap_return_2);

assign sf_r_14_fu_801_p2 = (trunc_ln734_fu_783_p1 + 6'd1);

assign sf_r_16_fu_917_p2 = (add_ln757_4_fu_912_p2 + zext_ln756_1_fu_908_p1);

assign sf_r_17_fu_941_p2 = (trunc_ln734_2_fu_923_p1 + 6'd1);

assign sf_r_19_fu_823_p3 = ((grp_fu_486_p3[0:0] == 1'b1) ? sf_r_14_fu_801_p2 : trunc_ln734_fu_783_p1);

assign sf_r_20_fu_963_p3 = ((grp_fu_486_p3[0:0] == 1'b1) ? sf_r_17_fu_941_p2 : trunc_ln734_2_fu_923_p1);

assign sf_r_fu_778_p2 = (add_ln757_fu_772_p2 + add_i321_i);

assign sign_3_fu_875_p2 = (xor_ln820_fu_869_p2 & sign_fu_754_p2);

assign sign_4_fu_894_p2 = (grp_positAdd_fu_406_ap_return_0 ^ empty_5);

assign sign_5_fu_1015_p2 = (xor_ln820_1_fu_1009_p2 & sign_4_fu_894_p2);

assign sign_fu_754_p2 = (grp_positCos_fu_382_ap_return_0 ^ empty_5);

assign tmp_5_i_fu_664_p3 = {{add_ln629_2_fu_658_p2[6:5]}};

assign tmp_fu_787_p3 = {{sf_r_fu_778_p2[6:5]}};

assign tmp_i_77_fu_703_p3 = {{add_ln629_1_fu_697_p2[6:5]}};

assign tmp_i_fu_615_p3 = {{add_ln629_fu_609_p2[6:5]}};

assign tmp_s_fu_927_p3 = {{sf_r_16_fu_917_p2[6:5]}};

assign trunc_ln734_2_fu_923_p1 = sf_r_16_fu_917_p2[5:0];

assign trunc_ln734_fu_783_p1 = sf_r_fu_778_p2[5:0];

assign xor_ln820_1_fu_1009_p2 = (isZero_1_fu_899_p2 ^ 1'd1);

assign xor_ln820_fu_869_p2 = (isZero_fu_759_p2 ^ 1'd1);

assign y_sign_1_fu_640_p2 = (in_sign_reg_1312 ^ 1'd1);

assign y_sign_3_fu_682_p2 = (grp_positMul_fu_430_ap_return_0 ^ 1'd1);

assign zext_ln748_4_fu_889_p1 = grp_positAdd_fu_406_ap_return_4;

assign zext_ln748_fu_749_p1 = grp_positCos_fu_382_ap_return_4;

assign zext_ln756_1_fu_908_p1 = grp_positAdd_fu_406_ap_return_3;

assign zext_ln756_fu_768_p1 = grp_positCos_fu_382_ap_return_3;

always @ (posedge ap_clk) begin
    conv3_i_i351_i_cast_reg_1238[59:30] <= 30'b000000000000000000000000000000;
end

endmodule //pFFT_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1
