// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pFFT_pReduceAngle (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_sign,
        x_regime,
        x_exponent,
        x_mantissa,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] x_sign;
input  [5:0] x_regime;
input  [0:0] x_exponent;
input  [29:0] x_mantissa;
output  [0:0] ap_return_0;
output  [5:0] ap_return_1;
output  [0:0] ap_return_2;
output  [29:0] ap_return_3;
output  [0:0] ap_return_4;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [5:0] x_regime_6_reg_144;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] x_exponent_4_reg_156;
reg   [29:0] y_mantissa_reg_168;
reg   [29:0] x_mantissa_read_reg_889;
reg   [29:0] x_mantissa_read_reg_889_pp0_iter1_reg;
reg   [29:0] x_mantissa_read_reg_889_pp0_iter2_reg;
reg   [29:0] x_mantissa_read_reg_889_pp0_iter3_reg;
reg   [29:0] x_mantissa_read_reg_889_pp0_iter4_reg;
reg   [29:0] x_mantissa_read_reg_889_pp0_iter5_reg;
reg   [29:0] x_mantissa_read_reg_889_pp0_iter6_reg;
reg   [29:0] x_mantissa_read_reg_889_pp0_iter7_reg;
reg   [0:0] x_exponent_read_reg_895;
reg   [0:0] x_exponent_read_reg_895_pp0_iter1_reg;
reg   [0:0] x_exponent_read_reg_895_pp0_iter2_reg;
reg   [0:0] x_exponent_read_reg_895_pp0_iter3_reg;
reg   [0:0] x_exponent_read_reg_895_pp0_iter4_reg;
reg   [0:0] x_exponent_read_reg_895_pp0_iter5_reg;
reg   [0:0] x_exponent_read_reg_895_pp0_iter6_reg;
reg   [0:0] x_exponent_read_reg_895_pp0_iter7_reg;
reg   [5:0] x_regime_read_reg_902;
reg   [5:0] x_regime_read_reg_902_pp0_iter1_reg;
reg   [5:0] x_regime_read_reg_902_pp0_iter2_reg;
reg   [5:0] x_regime_read_reg_902_pp0_iter3_reg;
reg   [5:0] x_regime_read_reg_902_pp0_iter4_reg;
reg   [5:0] x_regime_read_reg_902_pp0_iter5_reg;
reg   [5:0] x_regime_read_reg_902_pp0_iter6_reg;
reg   [5:0] x_regime_read_reg_902_pp0_iter7_reg;
reg   [0:0] x_sign_read_reg_909;
reg   [0:0] x_sign_read_reg_909_pp0_iter1_reg;
reg   [0:0] x_sign_read_reg_909_pp0_iter2_reg;
reg   [0:0] x_sign_read_reg_909_pp0_iter3_reg;
reg   [0:0] x_sign_read_reg_909_pp0_iter4_reg;
reg   [0:0] x_sign_read_reg_909_pp0_iter5_reg;
reg   [0:0] x_sign_read_reg_909_pp0_iter6_reg;
reg   [0:0] x_sign_read_reg_909_pp0_iter7_reg;
reg   [0:0] x_sign_read_reg_909_pp0_iter8_reg;
wire   [0:0] icmp_ln23_fu_397_p2;
reg   [0:0] icmp_ln23_reg_915;
reg   [0:0] icmp_ln23_reg_915_pp0_iter1_reg;
reg   [0:0] icmp_ln23_reg_915_pp0_iter2_reg;
reg   [0:0] icmp_ln23_reg_915_pp0_iter3_reg;
reg   [0:0] icmp_ln23_reg_915_pp0_iter4_reg;
reg   [0:0] icmp_ln23_reg_915_pp0_iter5_reg;
reg   [0:0] icmp_ln23_reg_915_pp0_iter6_reg;
reg   [0:0] icmp_ln23_reg_915_pp0_iter7_reg;
reg   [0:0] icmp_ln23_reg_915_pp0_iter8_reg;
wire   [0:0] absXGreaterEqual_5_fu_427_p2;
reg   [0:0] absXGreaterEqual_5_reg_919;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter1_reg;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter2_reg;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter3_reg;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter4_reg;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter5_reg;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter6_reg;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter7_reg;
reg   [0:0] absXGreaterEqual_5_reg_919_pp0_iter8_reg;
reg   [0:0] tmp_45_reg_923;
wire   [5:0] regime_fu_519_p3;
reg   [5:0] regime_reg_928;
wire   [93:0] tmp_i_fu_527_p8;
wire   [0:0] m_angle_sign_3_fu_579_p1;
reg   [0:0] m_angle_sign_3_reg_938;
reg   [0:0] m_angle_isZero_reg_944;
wire   [5:0] m_angle_regime_5_fu_591_p4;
reg   [5:0] m_angle_regime_5_reg_950;
wire   [0:0] m_angle_exponent_5_fu_601_p3;
reg   [0:0] m_angle_exponent_5_reg_956;
wire   [29:0] m_angle_mantissa_fu_609_p4;
reg   [29:0] m_angle_mantissa_reg_962;
wire   [0:0] retval_1_i_fu_695_p2;
reg   [0:0] retval_1_i_reg_968;
reg   [0:0] retval_1_i_reg_968_pp0_iter10_reg;
reg   [0:0] retval_1_i_reg_968_pp0_iter11_reg;
reg   [0:0] retval_1_i_reg_968_pp0_iter12_reg;
reg   [0:0] retval_1_i_reg_968_pp0_iter13_reg;
reg   [0:0] retval_1_i_reg_968_pp0_iter14_reg;
reg   [0:0] retval_1_i_reg_968_pp0_iter15_reg;
reg   [0:0] retval_1_i_reg_968_pp0_iter16_reg;
wire   [0:0] retval_1_i9_fu_737_p2;
reg   [0:0] retval_1_i9_reg_972;
reg   [0:0] retval_1_i9_reg_972_pp0_iter10_reg;
reg   [0:0] retval_1_i9_reg_972_pp0_iter11_reg;
reg   [0:0] retval_1_i9_reg_972_pp0_iter12_reg;
reg   [0:0] retval_1_i9_reg_972_pp0_iter13_reg;
reg   [0:0] retval_1_i9_reg_972_pp0_iter14_reg;
reg   [0:0] retval_1_i9_reg_972_pp0_iter15_reg;
reg   [0:0] retval_1_i9_reg_972_pp0_iter16_reg;
wire   [0:0] retval_1_i20_fu_809_p2;
reg   [0:0] retval_1_i20_reg_986;
reg   [0:0] retval_1_i20_reg_986_pp0_iter18_reg;
reg   [0:0] retval_1_i20_reg_986_pp0_iter19_reg;
reg   [0:0] retval_1_i20_reg_986_pp0_iter20_reg;
reg   [0:0] retval_1_i20_reg_986_pp0_iter21_reg;
reg   [0:0] retval_1_i20_reg_986_pp0_iter22_reg;
reg   [0:0] retval_1_i20_reg_986_pp0_iter23_reg;
reg   [0:0] retval_1_i20_reg_986_pp0_iter24_reg;
wire   [0:0] retval_1_i31_fu_853_p2;
reg   [0:0] retval_1_i31_reg_990;
reg   [0:0] retval_1_i31_reg_990_pp0_iter18_reg;
reg   [0:0] retval_1_i31_reg_990_pp0_iter19_reg;
reg   [0:0] retval_1_i31_reg_990_pp0_iter20_reg;
reg   [0:0] retval_1_i31_reg_990_pp0_iter21_reg;
reg   [0:0] retval_1_i31_reg_990_pp0_iter22_reg;
reg   [0:0] retval_1_i31_reg_990_pp0_iter23_reg;
reg   [0:0] retval_1_i31_reg_990_pp0_iter24_reg;
wire    grp_positAdd_fu_255_ap_start;
wire    grp_positAdd_fu_255_ap_done;
wire    grp_positAdd_fu_255_ap_idle;
wire    grp_positAdd_fu_255_ap_ready;
wire   [0:0] grp_positAdd_fu_255_ap_return_0;
wire   [0:0] grp_positAdd_fu_255_ap_return_1;
wire   [5:0] grp_positAdd_fu_255_ap_return_2;
wire   [0:0] grp_positAdd_fu_255_ap_return_3;
wire   [29:0] grp_positAdd_fu_255_ap_return_4;
wire    grp_positAdd_fu_275_ap_start;
wire    grp_positAdd_fu_275_ap_done;
wire    grp_positAdd_fu_275_ap_idle;
wire    grp_positAdd_fu_275_ap_ready;
reg   [0:0] grp_positAdd_fu_275_x_sign;
reg   [0:0] grp_positAdd_fu_275_y_sign_val;
wire   [0:0] grp_positAdd_fu_275_ap_return_0;
wire   [0:0] grp_positAdd_fu_275_ap_return_1;
wire   [5:0] grp_positAdd_fu_275_ap_return_2;
wire   [0:0] grp_positAdd_fu_275_ap_return_3;
wire   [29:0] grp_positAdd_fu_275_ap_return_4;
wire    grp_positAdd_fu_296_ap_start;
wire    grp_positAdd_fu_296_ap_done;
wire    grp_positAdd_fu_296_ap_idle;
wire    grp_positAdd_fu_296_ap_ready;
reg   [0:0] grp_positAdd_fu_296_x_sign;
reg   [0:0] grp_positAdd_fu_296_x_isZero;
reg   [5:0] grp_positAdd_fu_296_x_regime1;
reg   [0:0] grp_positAdd_fu_296_x_exponent2;
reg   [29:0] grp_positAdd_fu_296_x_mantissa3;
reg   [0:0] grp_positAdd_fu_296_y_sign_val;
reg   [0:0] grp_positAdd_fu_296_y_isZero_val;
reg   [5:0] grp_positAdd_fu_296_y_regime1_val;
reg   [0:0] grp_positAdd_fu_296_y_exponent2_val;
reg   [29:0] grp_positAdd_fu_296_y_mantissa3_val;
wire   [0:0] grp_positAdd_fu_296_ap_return_0;
wire   [0:0] grp_positAdd_fu_296_ap_return_1;
wire   [5:0] grp_positAdd_fu_296_ap_return_2;
wire   [0:0] grp_positAdd_fu_296_ap_return_3;
wire   [29:0] grp_positAdd_fu_296_ap_return_4;
reg   [93:0] ap_phi_mux_storemerge_in_i_phi_fu_127_p4;
wire   [93:0] tmp_18_i_fu_557_p10;
reg   [93:0] ap_phi_reg_pp0_iter9_storemerge_in_i_reg_124;
wire   [93:0] ap_phi_reg_pp0_iter0_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter1_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter2_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter3_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter4_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter5_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter6_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter7_storemerge_in_i_reg_124;
reg   [93:0] ap_phi_reg_pp0_iter8_storemerge_in_i_reg_124;
reg   [0:0] ap_phi_mux_x_sign_3_phi_fu_136_p6;
reg   [0:0] ap_phi_reg_pp0_iter17_x_sign_3_reg_133;
wire   [0:0] ap_phi_reg_pp0_iter0_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter1_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter2_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter3_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter4_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter5_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter6_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter7_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter8_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter9_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter10_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter11_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter12_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter13_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter14_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter15_x_sign_3_reg_133;
reg   [0:0] ap_phi_reg_pp0_iter16_x_sign_3_reg_133;
reg   [5:0] ap_phi_mux_x_regime_6_phi_fu_147_p6;
reg   [5:0] ap_phi_reg_pp0_iter17_x_regime_6_reg_144;
wire   [5:0] ap_phi_reg_pp0_iter0_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter1_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter2_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter3_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter4_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter5_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter6_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter7_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter8_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter9_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter10_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter11_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter12_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter13_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter14_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter15_x_regime_6_reg_144;
reg   [5:0] ap_phi_reg_pp0_iter16_x_regime_6_reg_144;
reg   [0:0] ap_phi_mux_x_exponent_4_phi_fu_159_p6;
reg   [0:0] ap_phi_reg_pp0_iter17_x_exponent_4_reg_156;
wire   [0:0] ap_phi_reg_pp0_iter0_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter1_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter2_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter3_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter4_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter5_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter6_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter7_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter8_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter9_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter10_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter11_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter12_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter13_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter14_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter15_x_exponent_4_reg_156;
reg   [0:0] ap_phi_reg_pp0_iter16_x_exponent_4_reg_156;
reg   [29:0] ap_phi_mux_y_mantissa_phi_fu_171_p6;
reg   [29:0] ap_phi_reg_pp0_iter17_y_mantissa_reg_168;
wire   [29:0] ap_phi_reg_pp0_iter0_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter1_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter2_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter3_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter4_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter5_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter6_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter7_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter8_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter9_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter10_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter11_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter12_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter13_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter14_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter15_y_mantissa_reg_168;
reg   [29:0] ap_phi_reg_pp0_iter16_y_mantissa_reg_168;
wire   [0:0] ap_phi_reg_pp0_iter0_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter1_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter2_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter3_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter4_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter5_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter6_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter7_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter8_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter9_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter10_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter11_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter12_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter13_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter14_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter15_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter16_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter17_y_isZero_reg_180;
reg   [0:0] ap_phi_reg_pp0_iter18_y_isZero_reg_180;
reg   [0:0] ap_phi_mux_ref_tmp_1440_2_phi_fu_195_p6;
reg   [0:0] ap_phi_reg_pp0_iter25_ref_tmp_1440_2_reg_192;
wire   [0:0] ap_phi_reg_pp0_iter0_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter1_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter2_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter3_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter4_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter5_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter6_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter7_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter8_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter9_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter10_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter11_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter12_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter13_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter14_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter15_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter16_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter17_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter18_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter19_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter20_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter21_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter22_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter23_ref_tmp_1440_2_reg_192;
reg   [0:0] ap_phi_reg_pp0_iter24_ref_tmp_1440_2_reg_192;
reg   [5:0] ap_phi_mux_ref_tmp_3_2_phi_fu_207_p6;
reg   [5:0] ap_phi_reg_pp0_iter25_ref_tmp_3_2_reg_204;
wire   [5:0] ap_phi_reg_pp0_iter0_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter1_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter2_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter3_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter4_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter5_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter6_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter7_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter8_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter9_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter10_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter11_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter12_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter13_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter14_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter15_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter16_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter17_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter18_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter19_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter20_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter21_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter22_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter23_ref_tmp_3_2_reg_204;
reg   [5:0] ap_phi_reg_pp0_iter24_ref_tmp_3_2_reg_204;
reg   [0:0] ap_phi_mux_ref_tmp_4_2_phi_fu_219_p6;
reg   [0:0] ap_phi_reg_pp0_iter25_ref_tmp_4_2_reg_216;
wire   [0:0] ap_phi_reg_pp0_iter0_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter1_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter2_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter3_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter4_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter5_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter6_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter7_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter8_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter9_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter10_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter11_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter12_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter13_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter14_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter15_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter16_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter17_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter18_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter19_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter20_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter21_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter22_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter23_ref_tmp_4_2_reg_216;
reg   [0:0] ap_phi_reg_pp0_iter24_ref_tmp_4_2_reg_216;
reg   [29:0] ap_phi_mux_ref_tmp_5_2_phi_fu_231_p6;
reg   [29:0] ap_phi_reg_pp0_iter25_ref_tmp_5_2_reg_228;
wire   [29:0] ap_phi_reg_pp0_iter0_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter1_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter2_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter3_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter4_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter5_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter6_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter7_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter8_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter9_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter10_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter11_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter12_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter13_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter14_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter15_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter16_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter17_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter18_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter19_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter20_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter21_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter22_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter23_ref_tmp_5_2_reg_228;
reg   [29:0] ap_phi_reg_pp0_iter24_ref_tmp_5_2_reg_228;
reg   [0:0] ap_phi_mux_negate_write_assign_phi_fu_244_p6;
reg   [0:0] ap_phi_reg_pp0_iter25_negate_write_assign_reg_240;
wire   [0:0] ap_phi_reg_pp0_iter0_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter1_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter2_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter3_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter4_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter5_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter6_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter7_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter8_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter9_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter10_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter11_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter12_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter13_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter14_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter15_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter16_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter17_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter18_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter19_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter20_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter21_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter22_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter23_negate_write_assign_reg_240;
reg   [0:0] ap_phi_reg_pp0_iter24_negate_write_assign_reg_240;
reg    grp_positAdd_fu_255_ap_start_reg;
reg    ap_predicate_op56_call_state3_state2;
wire    ap_block_pp0_stage0_ignoreCallOp56;
reg    grp_positAdd_fu_275_ap_start_reg;
reg    ap_predicate_op100_call_state11_state10;
wire    ap_block_pp0_stage0_ignoreCallOp100;
wire    ap_block_pp0_stage0_ignoreCallOp101;
reg    grp_positAdd_fu_296_ap_start_reg;
reg    ap_predicate_op154_call_state19_state18;
wire    ap_block_pp0_stage0_ignoreCallOp154;
wire    ap_block_pp0_stage0_ignoreCallOp155;
wire   [58:0] mul_ln675_fu_330_p0;
wire   [60:0] mul_ln675_fu_330_p1;
wire    ap_block_pp0_stage0;
wire   [4:0] tmp_fu_387_p4;
wire   [0:0] icmp_ln25_fu_415_p2;
wire   [0:0] xor_ln25_fu_409_p2;
wire   [0:0] and_ln25_fu_421_p2;
wire   [0:0] icmp_ln24_fu_403_p2;
wire   [58:0] shl_ln_fu_433_p3;
wire   [118:0] mul_ln675_fu_330_p2;
wire   [148:0] zext_ln680_fu_446_p1;
wire   [5:0] zext_ln675_fu_458_p1;
wire   [5:0] add_ln680_fu_468_p2;
wire   [5:0] select_ln680_fu_461_p3;
wire   [5:0] sf_r_fu_473_p2;
wire   [0:0] icmp_ln703_fu_479_p2;
wire   [5:0] add_ln800_fu_485_p2;
wire   [5:0] regime_14_fu_491_p3;
wire   [0:0] icmp_ln804_fu_505_p2;
wire   [0:0] icmp_ln803_fu_499_p2;
wire   [5:0] select_ln804_fu_511_p3;
wire   [4:0] tmp_48_fu_619_p4;
wire   [0:0] icmp_ln24_1_fu_635_p2;
wire   [0:0] icmp_ln25_1_fu_653_p2;
wire   [0:0] xor_ln25_1_fu_647_p2;
wire   [0:0] and_ln25_2_fu_659_p2;
wire   [0:0] icmp_ln23_1_fu_629_p2;
wire   [0:0] and_ln24_fu_641_p2;
wire   [0:0] or_ln24_fu_671_p2;
wire   [0:0] and_ln25_3_fu_665_p2;
wire   [0:0] absXGreaterEqual_fu_677_p2;
wire   [0:0] xor_ln27_fu_683_p2;
wire   [0:0] not_m_angle_sign_fu_689_p2;
wire   [0:0] icmp_ln25_2_fu_707_p2;
wire   [0:0] and_ln25_4_fu_713_p2;
wire   [0:0] icmp_ln23_2_fu_701_p2;
wire   [0:0] and_ln25_5_fu_719_p2;
wire   [0:0] absXGreaterEqual_1_fu_725_p2;
wire   [0:0] xor_ln27_1_fu_731_p2;
wire   [0:0] icmp_ln24_2_fu_749_p2;
wire   [0:0] icmp_ln25_3_fu_767_p2;
wire   [0:0] xor_ln25_2_fu_761_p2;
wire   [0:0] and_ln25_6_fu_773_p2;
wire   [0:0] icmp_ln23_3_fu_743_p2;
wire   [0:0] and_ln24_1_fu_755_p2;
wire   [0:0] or_ln24_1_fu_785_p2;
wire   [0:0] and_ln25_7_fu_779_p2;
wire   [0:0] absXGreaterEqual_2_fu_791_p2;
wire   [0:0] xor_ln27_2_fu_797_p2;
wire   [0:0] not_y_sign_fu_803_p2;
wire   [0:0] icmp_ln25_4_fu_823_p2;
wire   [0:0] and_ln25_8_fu_829_p2;
wire   [0:0] tmp_49_fu_815_p3;
wire   [0:0] and_ln25_9_fu_835_p2;
wire   [0:0] absXGreaterEqual_3_fu_841_p2;
wire   [0:0] xor_ln27_3_fu_847_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to24;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [118:0] mul_ln675_fu_330_p00;
reg    ap_condition_1301;
reg    ap_condition_1305;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 grp_positAdd_fu_255_ap_start_reg = 1'b0;
#0 grp_positAdd_fu_275_ap_start_reg = 1'b0;
#0 grp_positAdd_fu_296_ap_start_reg = 1'b0;
end

pFFT_positAdd grp_positAdd_fu_255(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_positAdd_fu_255_ap_start),
    .ap_done(grp_positAdd_fu_255_ap_done),
    .ap_idle(grp_positAdd_fu_255_ap_idle),
    .ap_ready(grp_positAdd_fu_255_ap_ready),
    .ap_ce(1'b1),
    .x_sign(1'd0),
    .x_isZero(1'd0),
    .x_regime1(x_regime_read_reg_902_pp0_iter1_reg),
    .x_exponent2(x_exponent_read_reg_895_pp0_iter1_reg),
    .x_mantissa3(x_mantissa_read_reg_889_pp0_iter1_reg),
    .y_sign_val(1'd1),
    .y_isZero_val(1'd0),
    .y_regime1_val(regime_reg_928),
    .y_exponent2_val(1'd0),
    .y_mantissa3_val(30'd842887333),
    .ap_return_0(grp_positAdd_fu_255_ap_return_0),
    .ap_return_1(grp_positAdd_fu_255_ap_return_1),
    .ap_return_2(grp_positAdd_fu_255_ap_return_2),
    .ap_return_3(grp_positAdd_fu_255_ap_return_3),
    .ap_return_4(grp_positAdd_fu_255_ap_return_4)
);

pFFT_positAdd grp_positAdd_fu_275(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_positAdd_fu_275_ap_start),
    .ap_done(grp_positAdd_fu_275_ap_done),
    .ap_idle(grp_positAdd_fu_275_ap_idle),
    .ap_ready(grp_positAdd_fu_275_ap_ready),
    .ap_ce(1'b1),
    .x_sign(grp_positAdd_fu_275_x_sign),
    .x_isZero(m_angle_isZero_reg_944),
    .x_regime1(m_angle_regime_5_reg_950),
    .x_exponent2(m_angle_exponent_5_reg_956),
    .x_mantissa3(m_angle_mantissa_reg_962),
    .y_sign_val(grp_positAdd_fu_275_y_sign_val),
    .y_isZero_val(1'd0),
    .y_regime1_val(6'd2),
    .y_exponent2_val(1'd0),
    .y_mantissa3_val(30'd842887333),
    .ap_return_0(grp_positAdd_fu_275_ap_return_0),
    .ap_return_1(grp_positAdd_fu_275_ap_return_1),
    .ap_return_2(grp_positAdd_fu_275_ap_return_2),
    .ap_return_3(grp_positAdd_fu_275_ap_return_3),
    .ap_return_4(grp_positAdd_fu_275_ap_return_4)
);

pFFT_positAdd grp_positAdd_fu_296(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_positAdd_fu_296_ap_start),
    .ap_done(grp_positAdd_fu_296_ap_done),
    .ap_idle(grp_positAdd_fu_296_ap_idle),
    .ap_ready(grp_positAdd_fu_296_ap_ready),
    .ap_ce(1'b1),
    .x_sign(grp_positAdd_fu_296_x_sign),
    .x_isZero(grp_positAdd_fu_296_x_isZero),
    .x_regime1(grp_positAdd_fu_296_x_regime1),
    .x_exponent2(grp_positAdd_fu_296_x_exponent2),
    .x_mantissa3(grp_positAdd_fu_296_x_mantissa3),
    .y_sign_val(grp_positAdd_fu_296_y_sign_val),
    .y_isZero_val(grp_positAdd_fu_296_y_isZero_val),
    .y_regime1_val(grp_positAdd_fu_296_y_regime1_val),
    .y_exponent2_val(grp_positAdd_fu_296_y_exponent2_val),
    .y_mantissa3_val(grp_positAdd_fu_296_y_mantissa3_val),
    .ap_return_0(grp_positAdd_fu_296_ap_return_0),
    .ap_return_1(grp_positAdd_fu_296_ap_return_1),
    .ap_return_2(grp_positAdd_fu_296_ap_return_2),
    .ap_return_3(grp_positAdd_fu_296_ap_return_3),
    .ap_return_4(grp_positAdd_fu_296_ap_return_4)
);

pFFT_mul_59ns_61ns_119_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 59 ),
    .din1_WIDTH( 61 ),
    .dout_WIDTH( 119 ))
mul_59ns_61ns_119_1_1_U84(
    .din0(mul_ln675_fu_330_p0),
    .din1(mul_ln675_fu_330_p1),
    .dout(mul_ln675_fu_330_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_positAdd_fu_255_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_predicate_op56_call_state3_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_positAdd_fu_255_ap_start_reg <= 1'b1;
        end else if ((grp_positAdd_fu_255_ap_ready == 1'b1)) begin
            grp_positAdd_fu_255_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_positAdd_fu_275_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_predicate_op100_call_state11_state10 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (retval_1_i_fu_695_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_positAdd_fu_275_ap_start_reg <= 1'b1;
        end else if ((grp_positAdd_fu_275_ap_ready == 1'b1)) begin
            grp_positAdd_fu_275_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_positAdd_fu_296_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_predicate_op154_call_state19_state18 == 1'b1) & (ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i20_fu_809_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_positAdd_fu_296_ap_start_reg <= 1'b1;
        end else if ((grp_positAdd_fu_296_ap_ready == 1'b1)) begin
            grp_positAdd_fu_296_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i9_fu_737_p2 == 1'd0) & (retval_1_i_fu_695_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter10_x_exponent_4_reg_156 <= ap_phi_mux_storemerge_in_i_phi_fu_127_p4[32'd32];
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter9_x_exponent_4_reg_156;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i9_fu_737_p2 == 1'd0) & (retval_1_i_fu_695_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter10_x_regime_6_reg_144 <= {{ap_phi_mux_storemerge_in_i_phi_fu_127_p4[29:24]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter9_x_regime_6_reg_144;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i9_fu_737_p2 == 1'd0) & (retval_1_i_fu_695_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter10_x_sign_3_reg_133 <= m_angle_sign_3_fu_579_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter9_x_sign_3_reg_133;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i9_fu_737_p2 == 1'd0) & (retval_1_i_fu_695_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter10_y_isZero_reg_180 <= ap_phi_mux_storemerge_in_i_phi_fu_127_p4[32'd8];
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_y_isZero_reg_180 <= ap_phi_reg_pp0_iter9_y_isZero_reg_180;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i9_fu_737_p2 == 1'd0) & (retval_1_i_fu_695_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter10_y_mantissa_reg_168 <= {{ap_phi_mux_storemerge_in_i_phi_fu_127_p4[93:64]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter9_y_mantissa_reg_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_phi_reg_pp0_iter18_y_isZero_reg_180 <= grp_positAdd_fu_275_ap_return_1;
    end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_y_isZero_reg_180 <= ap_phi_reg_pp0_iter17_y_isZero_reg_180;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i31_reg_990 == 1'd0) & (retval_1_i20_reg_986 == 1'd0))) begin
            ap_phi_reg_pp0_iter19_negate_write_assign_reg_240 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter19_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter18_negate_write_assign_reg_240;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i31_reg_990 == 1'd0) & (retval_1_i20_reg_986 == 1'd0))) begin
            ap_phi_reg_pp0_iter19_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter18_y_isZero_reg_180;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter19_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter18_ref_tmp_1440_2_reg_192;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i31_reg_990 == 1'd0) & (retval_1_i20_reg_986 == 1'd0))) begin
            ap_phi_reg_pp0_iter19_ref_tmp_3_2_reg_204 <= x_regime_6_reg_144;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter19_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter18_ref_tmp_3_2_reg_204;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i31_reg_990 == 1'd0) & (retval_1_i20_reg_986 == 1'd0))) begin
            ap_phi_reg_pp0_iter19_ref_tmp_4_2_reg_216 <= x_exponent_4_reg_156;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter19_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter18_ref_tmp_4_2_reg_216;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((retval_1_i31_reg_990 == 1'd0) & (retval_1_i20_reg_986 == 1'd0))) begin
            ap_phi_reg_pp0_iter19_ref_tmp_5_2_reg_228 <= y_mantissa_reg_168;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter19_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter18_ref_tmp_5_2_reg_228;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((1'd1 == absXGreaterEqual_5_reg_919_pp0_iter7_reg) | (icmp_ln23_reg_915_pp0_iter7_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter9_storemerge_in_i_reg_124 <= tmp_i_fu_527_p8;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter9_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter8_storemerge_in_i_reg_124;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        x_exponent_4_reg_156 <= grp_positAdd_fu_275_ap_return_3;
    end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter17_x_exponent_4_reg_156;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        x_regime_6_reg_144 <= grp_positAdd_fu_275_ap_return_2;
    end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_regime_6_reg_144 <= ap_phi_reg_pp0_iter17_x_regime_6_reg_144;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter17 == 1'b1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        y_mantissa_reg_168 <= grp_positAdd_fu_275_ap_return_4;
    end else if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        y_mantissa_reg_168 <= ap_phi_reg_pp0_iter17_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        absXGreaterEqual_5_reg_919 <= absXGreaterEqual_5_fu_427_p2;
        absXGreaterEqual_5_reg_919_pp0_iter1_reg <= absXGreaterEqual_5_reg_919;
        icmp_ln23_reg_915 <= icmp_ln23_fu_397_p2;
        icmp_ln23_reg_915_pp0_iter1_reg <= icmp_ln23_reg_915;
        regime_reg_928 <= regime_fu_519_p3;
        tmp_45_reg_923 <= zext_ln680_fu_446_p1[32'd118];
        x_exponent_read_reg_895 <= x_exponent;
        x_exponent_read_reg_895_pp0_iter1_reg <= x_exponent_read_reg_895;
        x_mantissa_read_reg_889 <= x_mantissa;
        x_mantissa_read_reg_889_pp0_iter1_reg <= x_mantissa_read_reg_889;
        x_regime_read_reg_902 <= x_regime;
        x_regime_read_reg_902_pp0_iter1_reg <= x_regime_read_reg_902;
        x_sign_read_reg_909 <= x_sign;
        x_sign_read_reg_909_pp0_iter1_reg <= x_sign_read_reg_909;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        absXGreaterEqual_5_reg_919_pp0_iter2_reg <= absXGreaterEqual_5_reg_919_pp0_iter1_reg;
        absXGreaterEqual_5_reg_919_pp0_iter3_reg <= absXGreaterEqual_5_reg_919_pp0_iter2_reg;
        absXGreaterEqual_5_reg_919_pp0_iter4_reg <= absXGreaterEqual_5_reg_919_pp0_iter3_reg;
        absXGreaterEqual_5_reg_919_pp0_iter5_reg <= absXGreaterEqual_5_reg_919_pp0_iter4_reg;
        absXGreaterEqual_5_reg_919_pp0_iter6_reg <= absXGreaterEqual_5_reg_919_pp0_iter5_reg;
        absXGreaterEqual_5_reg_919_pp0_iter7_reg <= absXGreaterEqual_5_reg_919_pp0_iter6_reg;
        absXGreaterEqual_5_reg_919_pp0_iter8_reg <= absXGreaterEqual_5_reg_919_pp0_iter7_reg;
        icmp_ln23_reg_915_pp0_iter2_reg <= icmp_ln23_reg_915_pp0_iter1_reg;
        icmp_ln23_reg_915_pp0_iter3_reg <= icmp_ln23_reg_915_pp0_iter2_reg;
        icmp_ln23_reg_915_pp0_iter4_reg <= icmp_ln23_reg_915_pp0_iter3_reg;
        icmp_ln23_reg_915_pp0_iter5_reg <= icmp_ln23_reg_915_pp0_iter4_reg;
        icmp_ln23_reg_915_pp0_iter6_reg <= icmp_ln23_reg_915_pp0_iter5_reg;
        icmp_ln23_reg_915_pp0_iter7_reg <= icmp_ln23_reg_915_pp0_iter6_reg;
        icmp_ln23_reg_915_pp0_iter8_reg <= icmp_ln23_reg_915_pp0_iter7_reg;
        m_angle_exponent_5_reg_956 <= ap_phi_mux_storemerge_in_i_phi_fu_127_p4[32'd32];
        m_angle_isZero_reg_944 <= ap_phi_mux_storemerge_in_i_phi_fu_127_p4[32'd8];
        m_angle_mantissa_reg_962 <= {{ap_phi_mux_storemerge_in_i_phi_fu_127_p4[93:64]}};
        m_angle_regime_5_reg_950 <= {{ap_phi_mux_storemerge_in_i_phi_fu_127_p4[29:24]}};
        m_angle_sign_3_reg_938 <= m_angle_sign_3_fu_579_p1;
        retval_1_i20_reg_986 <= retval_1_i20_fu_809_p2;
        retval_1_i20_reg_986_pp0_iter18_reg <= retval_1_i20_reg_986;
        retval_1_i20_reg_986_pp0_iter19_reg <= retval_1_i20_reg_986_pp0_iter18_reg;
        retval_1_i20_reg_986_pp0_iter20_reg <= retval_1_i20_reg_986_pp0_iter19_reg;
        retval_1_i20_reg_986_pp0_iter21_reg <= retval_1_i20_reg_986_pp0_iter20_reg;
        retval_1_i20_reg_986_pp0_iter22_reg <= retval_1_i20_reg_986_pp0_iter21_reg;
        retval_1_i20_reg_986_pp0_iter23_reg <= retval_1_i20_reg_986_pp0_iter22_reg;
        retval_1_i20_reg_986_pp0_iter24_reg <= retval_1_i20_reg_986_pp0_iter23_reg;
        retval_1_i31_reg_990 <= retval_1_i31_fu_853_p2;
        retval_1_i31_reg_990_pp0_iter18_reg <= retval_1_i31_reg_990;
        retval_1_i31_reg_990_pp0_iter19_reg <= retval_1_i31_reg_990_pp0_iter18_reg;
        retval_1_i31_reg_990_pp0_iter20_reg <= retval_1_i31_reg_990_pp0_iter19_reg;
        retval_1_i31_reg_990_pp0_iter21_reg <= retval_1_i31_reg_990_pp0_iter20_reg;
        retval_1_i31_reg_990_pp0_iter22_reg <= retval_1_i31_reg_990_pp0_iter21_reg;
        retval_1_i31_reg_990_pp0_iter23_reg <= retval_1_i31_reg_990_pp0_iter22_reg;
        retval_1_i31_reg_990_pp0_iter24_reg <= retval_1_i31_reg_990_pp0_iter23_reg;
        retval_1_i9_reg_972 <= retval_1_i9_fu_737_p2;
        retval_1_i9_reg_972_pp0_iter10_reg <= retval_1_i9_reg_972;
        retval_1_i9_reg_972_pp0_iter11_reg <= retval_1_i9_reg_972_pp0_iter10_reg;
        retval_1_i9_reg_972_pp0_iter12_reg <= retval_1_i9_reg_972_pp0_iter11_reg;
        retval_1_i9_reg_972_pp0_iter13_reg <= retval_1_i9_reg_972_pp0_iter12_reg;
        retval_1_i9_reg_972_pp0_iter14_reg <= retval_1_i9_reg_972_pp0_iter13_reg;
        retval_1_i9_reg_972_pp0_iter15_reg <= retval_1_i9_reg_972_pp0_iter14_reg;
        retval_1_i9_reg_972_pp0_iter16_reg <= retval_1_i9_reg_972_pp0_iter15_reg;
        retval_1_i_reg_968 <= retval_1_i_fu_695_p2;
        retval_1_i_reg_968_pp0_iter10_reg <= retval_1_i_reg_968;
        retval_1_i_reg_968_pp0_iter11_reg <= retval_1_i_reg_968_pp0_iter10_reg;
        retval_1_i_reg_968_pp0_iter12_reg <= retval_1_i_reg_968_pp0_iter11_reg;
        retval_1_i_reg_968_pp0_iter13_reg <= retval_1_i_reg_968_pp0_iter12_reg;
        retval_1_i_reg_968_pp0_iter14_reg <= retval_1_i_reg_968_pp0_iter13_reg;
        retval_1_i_reg_968_pp0_iter15_reg <= retval_1_i_reg_968_pp0_iter14_reg;
        retval_1_i_reg_968_pp0_iter16_reg <= retval_1_i_reg_968_pp0_iter15_reg;
        x_exponent_read_reg_895_pp0_iter2_reg <= x_exponent_read_reg_895_pp0_iter1_reg;
        x_exponent_read_reg_895_pp0_iter3_reg <= x_exponent_read_reg_895_pp0_iter2_reg;
        x_exponent_read_reg_895_pp0_iter4_reg <= x_exponent_read_reg_895_pp0_iter3_reg;
        x_exponent_read_reg_895_pp0_iter5_reg <= x_exponent_read_reg_895_pp0_iter4_reg;
        x_exponent_read_reg_895_pp0_iter6_reg <= x_exponent_read_reg_895_pp0_iter5_reg;
        x_exponent_read_reg_895_pp0_iter7_reg <= x_exponent_read_reg_895_pp0_iter6_reg;
        x_mantissa_read_reg_889_pp0_iter2_reg <= x_mantissa_read_reg_889_pp0_iter1_reg;
        x_mantissa_read_reg_889_pp0_iter3_reg <= x_mantissa_read_reg_889_pp0_iter2_reg;
        x_mantissa_read_reg_889_pp0_iter4_reg <= x_mantissa_read_reg_889_pp0_iter3_reg;
        x_mantissa_read_reg_889_pp0_iter5_reg <= x_mantissa_read_reg_889_pp0_iter4_reg;
        x_mantissa_read_reg_889_pp0_iter6_reg <= x_mantissa_read_reg_889_pp0_iter5_reg;
        x_mantissa_read_reg_889_pp0_iter7_reg <= x_mantissa_read_reg_889_pp0_iter6_reg;
        x_regime_read_reg_902_pp0_iter2_reg <= x_regime_read_reg_902_pp0_iter1_reg;
        x_regime_read_reg_902_pp0_iter3_reg <= x_regime_read_reg_902_pp0_iter2_reg;
        x_regime_read_reg_902_pp0_iter4_reg <= x_regime_read_reg_902_pp0_iter3_reg;
        x_regime_read_reg_902_pp0_iter5_reg <= x_regime_read_reg_902_pp0_iter4_reg;
        x_regime_read_reg_902_pp0_iter6_reg <= x_regime_read_reg_902_pp0_iter5_reg;
        x_regime_read_reg_902_pp0_iter7_reg <= x_regime_read_reg_902_pp0_iter6_reg;
        x_sign_read_reg_909_pp0_iter2_reg <= x_sign_read_reg_909_pp0_iter1_reg;
        x_sign_read_reg_909_pp0_iter3_reg <= x_sign_read_reg_909_pp0_iter2_reg;
        x_sign_read_reg_909_pp0_iter4_reg <= x_sign_read_reg_909_pp0_iter3_reg;
        x_sign_read_reg_909_pp0_iter5_reg <= x_sign_read_reg_909_pp0_iter4_reg;
        x_sign_read_reg_909_pp0_iter6_reg <= x_sign_read_reg_909_pp0_iter5_reg;
        x_sign_read_reg_909_pp0_iter7_reg <= x_sign_read_reg_909_pp0_iter6_reg;
        x_sign_read_reg_909_pp0_iter8_reg <= x_sign_read_reg_909_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter9_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter10_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter9_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter10_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter9_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter10_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter9_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter10_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter9_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter10_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter11_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter10_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter11_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter10_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter11_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter10_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter11_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter10_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter11_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter10_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter11_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter10_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter11_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter10_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter11_y_isZero_reg_180 <= ap_phi_reg_pp0_iter10_y_isZero_reg_180;
        ap_phi_reg_pp0_iter11_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter10_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter11_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter12_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter11_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter12_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter11_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter12_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter11_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter12_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter11_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter12_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter11_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter12_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter11_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter12_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter11_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter12_y_isZero_reg_180 <= ap_phi_reg_pp0_iter11_y_isZero_reg_180;
        ap_phi_reg_pp0_iter12_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter11_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter12_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter13_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter12_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter13_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter12_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter13_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter12_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter13_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter12_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter13_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter12_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter13_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter12_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter13_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter12_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter13_y_isZero_reg_180 <= ap_phi_reg_pp0_iter12_y_isZero_reg_180;
        ap_phi_reg_pp0_iter13_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter12_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter13_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter14_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter13_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter14_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter13_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter14_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter13_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter14_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter13_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter14_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter13_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter14_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter13_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter14_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter13_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter14_y_isZero_reg_180 <= ap_phi_reg_pp0_iter13_y_isZero_reg_180;
        ap_phi_reg_pp0_iter14_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter13_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter14_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter15_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter14_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter15_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter14_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter15_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter14_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter15_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter14_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter15_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter14_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter15_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter14_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter15_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter14_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter15_y_isZero_reg_180 <= ap_phi_reg_pp0_iter14_y_isZero_reg_180;
        ap_phi_reg_pp0_iter15_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter14_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter16_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter15_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter16_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter15_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter16_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter15_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter16_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter15_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter16_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter15_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter16_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter15_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter16_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter15_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter16_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter15_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter16_y_isZero_reg_180 <= ap_phi_reg_pp0_iter15_y_isZero_reg_180;
        ap_phi_reg_pp0_iter16_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter15_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter17_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter16_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter17_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter16_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter17_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter16_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter17_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter16_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter17_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter16_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter17_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter16_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter17_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter16_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter17_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter16_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter17_y_isZero_reg_180 <= ap_phi_reg_pp0_iter16_y_isZero_reg_180;
        ap_phi_reg_pp0_iter17_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter16_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter17_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter18_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter17_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter18_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter17_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter18_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter17_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter18_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter17_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter0_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter1_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter0_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter1_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter0_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter1_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter0_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter1_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter0_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter1_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter0_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter1_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter0_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter1_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter0_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter1_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter0_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter1_y_isZero_reg_180 <= ap_phi_reg_pp0_iter0_y_isZero_reg_180;
        ap_phi_reg_pp0_iter1_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter0_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter20_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter19_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter20_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter19_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter20_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter19_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter20_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter19_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter20_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter19_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter21_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter20_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter21_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter20_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter21_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter20_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter21_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter20_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter21_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter20_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter22_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter21_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter22_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter21_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter22_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter21_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter22_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter21_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter22_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter21_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter23_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter22_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter23_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter22_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter23_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter22_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter23_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter22_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter23_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter22_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter24_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter23_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter24_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter23_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter24_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter23_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter24_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter23_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter24_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter23_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter25_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter24_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter25_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter24_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter25_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter24_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter25_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter24_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter25_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter24_ref_tmp_5_2_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter1_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter2_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter1_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter2_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter1_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter2_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter1_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter2_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter1_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter2_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter1_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter2_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter1_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter2_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter1_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter2_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter1_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter2_y_isZero_reg_180 <= ap_phi_reg_pp0_iter1_y_isZero_reg_180;
        ap_phi_reg_pp0_iter2_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter1_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter2_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter3_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter2_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter3_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter2_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter3_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter2_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter3_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter2_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter3_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter2_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter3_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter2_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter3_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter2_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter3_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter2_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter3_y_isZero_reg_180 <= ap_phi_reg_pp0_iter2_y_isZero_reg_180;
        ap_phi_reg_pp0_iter3_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter2_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter3_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter4_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter3_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter4_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter3_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter4_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter3_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter4_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter3_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter4_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter3_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter4_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter3_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter4_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter3_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter4_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter3_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter4_y_isZero_reg_180 <= ap_phi_reg_pp0_iter3_y_isZero_reg_180;
        ap_phi_reg_pp0_iter4_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter3_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter4_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter5_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter4_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter5_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter4_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter5_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter4_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter5_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter4_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter5_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter4_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter5_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter4_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter5_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter4_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter5_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter4_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter5_y_isZero_reg_180 <= ap_phi_reg_pp0_iter4_y_isZero_reg_180;
        ap_phi_reg_pp0_iter5_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter4_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter5_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter6_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter5_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter6_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter5_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter6_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter5_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter6_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter5_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter6_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter5_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter6_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter5_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter6_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter5_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter6_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter5_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter6_y_isZero_reg_180 <= ap_phi_reg_pp0_iter5_y_isZero_reg_180;
        ap_phi_reg_pp0_iter6_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter5_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter6_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter7_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter6_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter7_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter6_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter7_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter6_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter7_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter6_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter7_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter6_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter7_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter6_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter7_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter6_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter7_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter6_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter7_y_isZero_reg_180 <= ap_phi_reg_pp0_iter6_y_isZero_reg_180;
        ap_phi_reg_pp0_iter7_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter6_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter7_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter8_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter7_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter8_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter7_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter8_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter7_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter8_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter7_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter8_storemerge_in_i_reg_124 <= ap_phi_reg_pp0_iter7_storemerge_in_i_reg_124;
        ap_phi_reg_pp0_iter8_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter7_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter8_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter7_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter8_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter7_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter8_y_isZero_reg_180 <= ap_phi_reg_pp0_iter7_y_isZero_reg_180;
        ap_phi_reg_pp0_iter8_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter7_y_mantissa_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_negate_write_assign_reg_240 <= ap_phi_reg_pp0_iter8_negate_write_assign_reg_240;
        ap_phi_reg_pp0_iter9_ref_tmp_1440_2_reg_192 <= ap_phi_reg_pp0_iter8_ref_tmp_1440_2_reg_192;
        ap_phi_reg_pp0_iter9_ref_tmp_3_2_reg_204 <= ap_phi_reg_pp0_iter8_ref_tmp_3_2_reg_204;
        ap_phi_reg_pp0_iter9_ref_tmp_4_2_reg_216 <= ap_phi_reg_pp0_iter8_ref_tmp_4_2_reg_216;
        ap_phi_reg_pp0_iter9_ref_tmp_5_2_reg_228 <= ap_phi_reg_pp0_iter8_ref_tmp_5_2_reg_228;
        ap_phi_reg_pp0_iter9_x_exponent_4_reg_156 <= ap_phi_reg_pp0_iter8_x_exponent_4_reg_156;
        ap_phi_reg_pp0_iter9_x_regime_6_reg_144 <= ap_phi_reg_pp0_iter8_x_regime_6_reg_144;
        ap_phi_reg_pp0_iter9_x_sign_3_reg_133 <= ap_phi_reg_pp0_iter8_x_sign_3_reg_133;
        ap_phi_reg_pp0_iter9_y_isZero_reg_180 <= ap_phi_reg_pp0_iter8_y_isZero_reg_180;
        ap_phi_reg_pp0_iter9_y_mantissa_reg_168 <= ap_phi_reg_pp0_iter8_y_mantissa_reg_168;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to24 = 1'b1;
    end else begin
        ap_idle_pp0_0to24 = 1'b0;
    end
end

always @ (*) begin
    if (((retval_1_i20_reg_986_pp0_iter24_reg == 1'd1) | ((retval_1_i31_reg_990_pp0_iter24_reg == 1'd1) & (retval_1_i20_reg_986_pp0_iter24_reg == 1'd0)))) begin
        ap_phi_mux_negate_write_assign_phi_fu_244_p6 = 1'd1;
    end else begin
        ap_phi_mux_negate_write_assign_phi_fu_244_p6 = ap_phi_reg_pp0_iter25_negate_write_assign_reg_240;
    end
end

always @ (*) begin
    if (((retval_1_i20_reg_986_pp0_iter24_reg == 1'd1) | ((retval_1_i31_reg_990_pp0_iter24_reg == 1'd1) & (retval_1_i20_reg_986_pp0_iter24_reg == 1'd0)))) begin
        ap_phi_mux_ref_tmp_1440_2_phi_fu_195_p6 = grp_positAdd_fu_296_ap_return_1;
    end else begin
        ap_phi_mux_ref_tmp_1440_2_phi_fu_195_p6 = ap_phi_reg_pp0_iter25_ref_tmp_1440_2_reg_192;
    end
end

always @ (*) begin
    if (((retval_1_i20_reg_986_pp0_iter24_reg == 1'd1) | ((retval_1_i31_reg_990_pp0_iter24_reg == 1'd1) & (retval_1_i20_reg_986_pp0_iter24_reg == 1'd0)))) begin
        ap_phi_mux_ref_tmp_3_2_phi_fu_207_p6 = grp_positAdd_fu_296_ap_return_2;
    end else begin
        ap_phi_mux_ref_tmp_3_2_phi_fu_207_p6 = ap_phi_reg_pp0_iter25_ref_tmp_3_2_reg_204;
    end
end

always @ (*) begin
    if (((retval_1_i20_reg_986_pp0_iter24_reg == 1'd1) | ((retval_1_i31_reg_990_pp0_iter24_reg == 1'd1) & (retval_1_i20_reg_986_pp0_iter24_reg == 1'd0)))) begin
        ap_phi_mux_ref_tmp_4_2_phi_fu_219_p6 = grp_positAdd_fu_296_ap_return_3;
    end else begin
        ap_phi_mux_ref_tmp_4_2_phi_fu_219_p6 = ap_phi_reg_pp0_iter25_ref_tmp_4_2_reg_216;
    end
end

always @ (*) begin
    if (((retval_1_i20_reg_986_pp0_iter24_reg == 1'd1) | ((retval_1_i31_reg_990_pp0_iter24_reg == 1'd1) & (retval_1_i20_reg_986_pp0_iter24_reg == 1'd0)))) begin
        ap_phi_mux_ref_tmp_5_2_phi_fu_231_p6 = grp_positAdd_fu_296_ap_return_4;
    end else begin
        ap_phi_mux_ref_tmp_5_2_phi_fu_231_p6 = ap_phi_reg_pp0_iter25_ref_tmp_5_2_reg_228;
    end
end

always @ (*) begin
    if (((1'd0 == absXGreaterEqual_5_reg_919_pp0_iter8_reg) & (icmp_ln23_reg_915_pp0_iter8_reg == 1'd0))) begin
        ap_phi_mux_storemerge_in_i_phi_fu_127_p4 = tmp_18_i_fu_557_p10;
    end else begin
        ap_phi_mux_storemerge_in_i_phi_fu_127_p4 = ap_phi_reg_pp0_iter9_storemerge_in_i_reg_124;
    end
end

always @ (*) begin
    if (((retval_1_i_reg_968_pp0_iter16_reg == 1'd1) | ((retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0)))) begin
        ap_phi_mux_x_exponent_4_phi_fu_159_p6 = grp_positAdd_fu_275_ap_return_3;
    end else begin
        ap_phi_mux_x_exponent_4_phi_fu_159_p6 = ap_phi_reg_pp0_iter17_x_exponent_4_reg_156;
    end
end

always @ (*) begin
    if (((retval_1_i_reg_968_pp0_iter16_reg == 1'd1) | ((retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0)))) begin
        ap_phi_mux_x_regime_6_phi_fu_147_p6 = grp_positAdd_fu_275_ap_return_2;
    end else begin
        ap_phi_mux_x_regime_6_phi_fu_147_p6 = ap_phi_reg_pp0_iter17_x_regime_6_reg_144;
    end
end

always @ (*) begin
    if (((retval_1_i_reg_968_pp0_iter16_reg == 1'd1) | ((retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0)))) begin
        ap_phi_mux_x_sign_3_phi_fu_136_p6 = grp_positAdd_fu_275_ap_return_0;
    end else begin
        ap_phi_mux_x_sign_3_phi_fu_136_p6 = ap_phi_reg_pp0_iter17_x_sign_3_reg_133;
    end
end

always @ (*) begin
    if (((retval_1_i_reg_968_pp0_iter16_reg == 1'd1) | ((retval_1_i9_reg_972_pp0_iter16_reg == 1'd1) & (retval_1_i_reg_968_pp0_iter16_reg == 1'd0)))) begin
        ap_phi_mux_y_mantissa_phi_fu_171_p6 = grp_positAdd_fu_275_ap_return_4;
    end else begin
        ap_phi_mux_y_mantissa_phi_fu_171_p6 = ap_phi_reg_pp0_iter17_y_mantissa_reg_168;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to24 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter10 == 1'b1)) begin
        if (((retval_1_i_reg_968 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp101))) begin
            grp_positAdd_fu_275_x_sign = m_angle_sign_3_reg_938;
        end else if ((1'b1 == ap_condition_1301)) begin
            grp_positAdd_fu_275_x_sign = 1'd1;
        end else begin
            grp_positAdd_fu_275_x_sign = 'bx;
        end
    end else begin
        grp_positAdd_fu_275_x_sign = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter10 == 1'b1)) begin
        if (((retval_1_i_reg_968 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp101))) begin
            grp_positAdd_fu_275_y_sign_val = 1'd1;
        end else if ((1'b1 == ap_condition_1301)) begin
            grp_positAdd_fu_275_y_sign_val = 1'd0;
        end else begin
            grp_positAdd_fu_275_y_sign_val = 'bx;
        end
    end else begin
        grp_positAdd_fu_275_y_sign_val = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_x_exponent2 = 1'd0;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_x_exponent2 = x_exponent_4_reg_156;
        end else begin
            grp_positAdd_fu_296_x_exponent2 = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_x_exponent2 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_x_isZero = 1'd0;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_x_isZero = ap_phi_reg_pp0_iter18_y_isZero_reg_180;
        end else begin
            grp_positAdd_fu_296_x_isZero = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_x_isZero = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_x_mantissa3 = 30'd842887333;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_x_mantissa3 = y_mantissa_reg_168;
        end else begin
            grp_positAdd_fu_296_x_mantissa3 = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_x_mantissa3 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_x_regime1 = 6'd1;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_x_regime1 = x_regime_6_reg_144;
        end else begin
            grp_positAdd_fu_296_x_regime1 = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_x_regime1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_x_sign = 1'd0;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_x_sign = 1'd1;
        end else begin
            grp_positAdd_fu_296_x_sign = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_x_sign = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_y_exponent2_val = x_exponent_4_reg_156;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_y_exponent2_val = 1'd0;
        end else begin
            grp_positAdd_fu_296_y_exponent2_val = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_y_exponent2_val = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_y_isZero_val = ap_phi_reg_pp0_iter18_y_isZero_reg_180;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_y_isZero_val = 1'd0;
        end else begin
            grp_positAdd_fu_296_y_isZero_val = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_y_isZero_val = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_y_mantissa3_val = y_mantissa_reg_168;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_y_mantissa3_val = 30'd842887333;
        end else begin
            grp_positAdd_fu_296_y_mantissa3_val = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_y_mantissa3_val = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_y_regime1_val = x_regime_6_reg_144;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_y_regime1_val = 6'd1;
        end else begin
            grp_positAdd_fu_296_y_regime1_val = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_y_regime1_val = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
        if (((retval_1_i20_reg_986 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp155))) begin
            grp_positAdd_fu_296_y_sign_val = 1'd1;
        end else if ((1'b1 == ap_condition_1305)) begin
            grp_positAdd_fu_296_y_sign_val = 1'd0;
        end else begin
            grp_positAdd_fu_296_y_sign_val = 'bx;
        end
    end else begin
        grp_positAdd_fu_296_y_sign_val = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign absXGreaterEqual_1_fu_725_p2 = (icmp_ln23_2_fu_701_p2 | and_ln25_5_fu_719_p2);

assign absXGreaterEqual_2_fu_791_p2 = (or_ln24_1_fu_785_p2 | and_ln25_7_fu_779_p2);

assign absXGreaterEqual_3_fu_841_p2 = (tmp_49_fu_815_p3 | and_ln25_9_fu_835_p2);

assign absXGreaterEqual_5_fu_427_p2 = (icmp_ln24_fu_403_p2 & and_ln25_fu_421_p2);

assign absXGreaterEqual_fu_677_p2 = (or_ln24_fu_671_p2 | and_ln25_3_fu_665_p2);

assign add_ln680_fu_468_p2 = (zext_ln675_fu_458_p1 + x_regime_read_reg_902);

assign add_ln800_fu_485_p2 = (sf_r_fu_473_p2 + 6'd2);

assign and_ln24_1_fu_755_p2 = (icmp_ln24_2_fu_749_p2 & ap_phi_mux_x_exponent_4_phi_fu_159_p6);

assign and_ln24_fu_641_p2 = (m_angle_exponent_5_fu_601_p3 & icmp_ln24_1_fu_635_p2);

assign and_ln25_2_fu_659_p2 = (xor_ln25_1_fu_647_p2 & icmp_ln25_1_fu_653_p2);

assign and_ln25_3_fu_665_p2 = (icmp_ln24_1_fu_635_p2 & and_ln25_2_fu_659_p2);

assign and_ln25_4_fu_713_p2 = (xor_ln25_1_fu_647_p2 & icmp_ln25_2_fu_707_p2);

assign and_ln25_5_fu_719_p2 = (icmp_ln24_1_fu_635_p2 & and_ln25_4_fu_713_p2);

assign and_ln25_6_fu_773_p2 = (xor_ln25_2_fu_761_p2 & icmp_ln25_3_fu_767_p2);

assign and_ln25_7_fu_779_p2 = (icmp_ln24_2_fu_749_p2 & and_ln25_6_fu_773_p2);

assign and_ln25_8_fu_829_p2 = (xor_ln25_2_fu_761_p2 & icmp_ln25_4_fu_823_p2);

assign and_ln25_9_fu_835_p2 = (icmp_ln24_2_fu_749_p2 & and_ln25_8_fu_829_p2);

assign and_ln25_fu_421_p2 = (xor_ln25_fu_409_p2 & icmp_ln25_fu_415_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp100 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp101 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp154 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp155 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp56 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1301 = ((retval_1_i9_reg_972 == 1'd1) & (retval_1_i_reg_968 == 1'd0) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp100));
end

always @ (*) begin
    ap_condition_1305 = ((retval_1_i31_reg_990 == 1'd1) & (retval_1_i20_reg_986 == 1'd0) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp154));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_negate_write_assign_reg_240 = 'bx;

assign ap_phi_reg_pp0_iter0_ref_tmp_1440_2_reg_192 = 'bx;

assign ap_phi_reg_pp0_iter0_ref_tmp_3_2_reg_204 = 'bx;

assign ap_phi_reg_pp0_iter0_ref_tmp_4_2_reg_216 = 'bx;

assign ap_phi_reg_pp0_iter0_ref_tmp_5_2_reg_228 = 'bx;

assign ap_phi_reg_pp0_iter0_storemerge_in_i_reg_124 = 'bx;

assign ap_phi_reg_pp0_iter0_x_exponent_4_reg_156 = 'bx;

assign ap_phi_reg_pp0_iter0_x_regime_6_reg_144 = 'bx;

assign ap_phi_reg_pp0_iter0_x_sign_3_reg_133 = 'bx;

assign ap_phi_reg_pp0_iter0_y_isZero_reg_180 = 'bx;

assign ap_phi_reg_pp0_iter0_y_mantissa_reg_168 = 'bx;

always @ (*) begin
    ap_predicate_op100_call_state11_state10 = ((retval_1_i9_fu_737_p2 == 1'd1) & (retval_1_i_fu_695_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op154_call_state19_state18 = ((retval_1_i31_fu_853_p2 == 1'd1) & (retval_1_i20_fu_809_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op56_call_state3_state2 = ((1'd0 == absXGreaterEqual_5_reg_919) & (icmp_ln23_reg_915 == 1'd0));
end

assign ap_return_0 = ap_phi_mux_ref_tmp_1440_2_phi_fu_195_p6;

assign ap_return_1 = ap_phi_mux_ref_tmp_3_2_phi_fu_207_p6;

assign ap_return_2 = ap_phi_mux_ref_tmp_4_2_phi_fu_219_p6;

assign ap_return_3 = ap_phi_mux_ref_tmp_5_2_phi_fu_231_p6;

assign ap_return_4 = ap_phi_mux_negate_write_assign_phi_fu_244_p6;

assign grp_positAdd_fu_255_ap_start = grp_positAdd_fu_255_ap_start_reg;

assign grp_positAdd_fu_275_ap_start = grp_positAdd_fu_275_ap_start_reg;

assign grp_positAdd_fu_296_ap_start = grp_positAdd_fu_296_ap_start_reg;

assign icmp_ln23_1_fu_629_p2 = (($signed(tmp_48_fu_619_p4) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln23_2_fu_701_p2 = (($signed(m_angle_regime_5_fu_591_p4) < $signed(6'd1)) ? 1'b1 : 1'b0);

assign icmp_ln23_3_fu_743_p2 = (($signed(ap_phi_mux_x_regime_6_phi_fu_147_p6) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_397_p2 = (($signed(tmp_fu_387_p4) < $signed(5'd1)) ? 1'b1 : 1'b0);

assign icmp_ln24_1_fu_635_p2 = ((m_angle_regime_5_fu_591_p4 == 6'd1) ? 1'b1 : 1'b0);

assign icmp_ln24_2_fu_749_p2 = ((ap_phi_mux_x_regime_6_phi_fu_147_p6 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_403_p2 = ((x_regime == 6'd2) ? 1'b1 : 1'b0);

assign icmp_ln25_1_fu_653_p2 = ((m_angle_mantissa_fu_609_p4 > 30'd842887333) ? 1'b1 : 1'b0);

assign icmp_ln25_2_fu_707_p2 = ((m_angle_mantissa_fu_609_p4 < 30'd842887333) ? 1'b1 : 1'b0);

assign icmp_ln25_3_fu_767_p2 = ((ap_phi_mux_y_mantissa_phi_fu_171_p6 > 30'd842887333) ? 1'b1 : 1'b0);

assign icmp_ln25_4_fu_823_p2 = ((ap_phi_mux_y_mantissa_phi_fu_171_p6 < 30'd842887333) ? 1'b1 : 1'b0);

assign icmp_ln25_fu_415_p2 = ((x_mantissa < 30'd842887333) ? 1'b1 : 1'b0);

assign icmp_ln703_fu_479_p2 = (($signed(sf_r_fu_473_p2) < $signed(6'd30)) ? 1'b1 : 1'b0);

assign icmp_ln803_fu_499_p2 = (($signed(regime_14_fu_491_p3) > $signed(6'd29)) ? 1'b1 : 1'b0);

assign icmp_ln804_fu_505_p2 = (($signed(regime_14_fu_491_p3) > $signed(6'd34)) ? 1'b1 : 1'b0);

assign m_angle_exponent_5_fu_601_p3 = ap_phi_mux_storemerge_in_i_phi_fu_127_p4[32'd32];

assign m_angle_mantissa_fu_609_p4 = {{ap_phi_mux_storemerge_in_i_phi_fu_127_p4[93:64]}};

assign m_angle_regime_5_fu_591_p4 = {{ap_phi_mux_storemerge_in_i_phi_fu_127_p4[29:24]}};

assign m_angle_sign_3_fu_579_p1 = ap_phi_mux_storemerge_in_i_phi_fu_127_p4[0:0];

assign mul_ln675_fu_330_p0 = mul_ln675_fu_330_p00;

assign mul_ln675_fu_330_p00 = shl_ln_fu_433_p3;

assign mul_ln675_fu_330_p1 = 119'd734344906382274626;

assign not_m_angle_sign_fu_689_p2 = (m_angle_sign_3_fu_579_p1 ^ 1'd1);

assign not_y_sign_fu_803_p2 = (ap_phi_mux_x_sign_3_phi_fu_136_p6 ^ 1'd1);

assign or_ln24_1_fu_785_p2 = (icmp_ln23_3_fu_743_p2 | and_ln24_1_fu_755_p2);

assign or_ln24_fu_671_p2 = (icmp_ln23_1_fu_629_p2 | and_ln24_fu_641_p2);

assign regime_14_fu_491_p3 = ((icmp_ln703_fu_479_p2[0:0] == 1'b1) ? add_ln800_fu_485_p2 : 6'd32);

assign regime_fu_519_p3 = ((icmp_ln803_fu_499_p2[0:0] == 1'b1) ? 6'd30 : select_ln804_fu_511_p3);

assign retval_1_i20_fu_809_p2 = (xor_ln27_2_fu_797_p2 & not_y_sign_fu_803_p2);

assign retval_1_i31_fu_853_p2 = (xor_ln27_3_fu_847_p2 & ap_phi_mux_x_sign_3_phi_fu_136_p6);

assign retval_1_i9_fu_737_p2 = (xor_ln27_1_fu_731_p2 & m_angle_sign_3_fu_579_p1);

assign retval_1_i_fu_695_p2 = (xor_ln27_fu_683_p2 & not_m_angle_sign_fu_689_p2);

assign select_ln680_fu_461_p3 = ((tmp_45_reg_923[0:0] == 1'b1) ? 6'd62 : 6'd61);

assign select_ln804_fu_511_p3 = ((icmp_ln804_fu_505_p2[0:0] == 1'b1) ? regime_14_fu_491_p3 : 6'd34);

assign sf_r_fu_473_p2 = (add_ln680_fu_468_p2 + select_ln680_fu_461_p3);

assign shl_ln_fu_433_p3 = {{x_mantissa}, {29'd0}};

assign tmp_18_i_fu_557_p10 = {{{{{{{{{grp_positAdd_fu_255_ap_return_4}, {31'd0}}, {grp_positAdd_fu_255_ap_return_3}}, {2'd0}}, {grp_positAdd_fu_255_ap_return_2}}, {15'd0}}, {grp_positAdd_fu_255_ap_return_1}}, {7'd0}}, {x_sign_read_reg_909_pp0_iter8_reg}};

assign tmp_48_fu_619_p4 = {{ap_phi_mux_storemerge_in_i_phi_fu_127_p4[29:25]}};

assign tmp_49_fu_815_p3 = ap_phi_mux_x_regime_6_phi_fu_147_p6[32'd5];

assign tmp_fu_387_p4 = {{x_regime[5:1]}};

assign tmp_i_fu_527_p8 = {{{{{{{x_mantissa_read_reg_889_pp0_iter7_reg}, {31'd0}}, {x_exponent_read_reg_895_pp0_iter7_reg}}, {2'd0}}, {x_regime_read_reg_902_pp0_iter7_reg}}, {23'd0}}, {x_sign_read_reg_909_pp0_iter7_reg}};

assign xor_ln25_1_fu_647_p2 = (m_angle_exponent_5_fu_601_p3 ^ 1'd1);

assign xor_ln25_2_fu_761_p2 = (ap_phi_mux_x_exponent_4_phi_fu_159_p6 ^ 1'd1);

assign xor_ln25_fu_409_p2 = (x_exponent ^ 1'd1);

assign xor_ln27_1_fu_731_p2 = (1'd1 ^ absXGreaterEqual_1_fu_725_p2);

assign xor_ln27_2_fu_797_p2 = (ap_phi_mux_x_sign_3_phi_fu_136_p6 ^ absXGreaterEqual_2_fu_791_p2);

assign xor_ln27_3_fu_847_p2 = (1'd1 ^ absXGreaterEqual_3_fu_841_p2);

assign xor_ln27_fu_683_p2 = (m_angle_sign_3_fu_579_p1 ^ absXGreaterEqual_fu_677_p2);

assign zext_ln675_fu_458_p1 = x_exponent_read_reg_895;

assign zext_ln680_fu_446_p1 = mul_ln675_fu_330_p2;

endmodule //pFFT_pReduceAngle
