// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dIFFT_generic_fmod_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] x;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] ret_5_fu_101_p1;
reg   [63:0] ret_5_reg_329;
wire   [51:0] fz_sig_fu_113_p1;
reg   [51:0] fz_sig_reg_335;
wire   [0:0] isF_e_x_fu_117_p2;
reg   [0:0] isF_e_x_reg_340;
wire   [0:0] isyBx_e_fu_123_p2;
reg   [0:0] isyBx_e_reg_344;
wire   [0:0] or_ln267_fu_141_p2;
reg   [0:0] or_ln267_reg_348;
wire   [0:0] or_ln271_fu_153_p2;
reg   [0:0] or_ln271_reg_352;
wire   [52:0] ap_mx_fu_169_p3;
reg   [52:0] ap_mx_reg_356;
wire   [9:0] n_fu_178_p2;
reg   [9:0] n_reg_361;
wire   [63:0] t_2_fu_185_p4;
wire    ap_CS_fsm_state2;
wire   [63:0] t_3_fu_194_p3;
wire    ap_CS_fsm_state3;
wire   [63:0] t_fu_315_p3;
wire    ap_CS_fsm_state6;
wire    grp_generic_fmod_double_Pipeline_1_fu_87_ap_start;
wire    grp_generic_fmod_double_Pipeline_1_fu_87_ap_done;
wire    grp_generic_fmod_double_Pipeline_1_fu_87_ap_idle;
wire    grp_generic_fmod_double_Pipeline_1_fu_87_ap_ready;
wire   [53:0] grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out;
wire    grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out_ap_vld;
reg   [63:0] ap_phi_mux_retval_1_in_phi_fu_73_p12;
reg   [63:0] retval_1_in_reg_70;
wire   [63:0] t_4_fu_302_p3;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln319_fu_205_p2;
wire   [63:0] t_5_fu_291_p4;
reg    grp_generic_fmod_double_Pipeline_1_fu_87_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [10:0] fz_exp_fu_105_p3;
wire   [0:0] icmp_ln267_fu_129_p2;
wire   [0:0] icmp_ln267_1_fu_135_p2;
wire   [0:0] icmp_ln271_fu_147_p2;
wire   [9:0] fz_exp_cast_fu_159_p4;
wire   [0:0] grp_fu_94_p3;
wire   [53:0] tmp_5_fu_211_p3;
wire   [6:0] trunc_ln324_1_fu_223_p1;
wire   [5:0] trunc_ln324_fu_219_p1;
wire   [6:0] add_ln325_fu_227_p2;
wire  signed [31:0] sext_ln325_fu_249_p1;
wire   [53:0] zext_ln325_fu_253_p1;
wire   [53:0] shl_ln325_fu_257_p2;
wire   [0:0] icmp_ln325_fu_233_p2;
wire   [51:0] trunc_ln325_1_fu_239_p4;
wire   [51:0] empty_fu_263_p1;
wire   [6:0] sub_ln327_fu_275_p2;
wire  signed [10:0] sext_ln327_fu_281_p1;
wire   [10:0] fz_exp_1_fu_285_p2;
wire   [51:0] ap_mx_2_fu_267_p3;
wire   [63:0] bitcast_ln497_fu_311_p1;
reg   [63:0] ap_return_preg;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_condition_125;
wire   [53:0] tmp_5_fu_211_p0;
wire   [0:0] tmp_5_fu_211_p2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_generic_fmod_double_Pipeline_1_fu_87_ap_start_reg = 1'b0;
#0 ap_return_preg = 64'd0;
end

dIFFT_generic_fmod_double_Pipeline_1 grp_generic_fmod_double_Pipeline_1_fu_87(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_generic_fmod_double_Pipeline_1_fu_87_ap_start),
    .ap_done(grp_generic_fmod_double_Pipeline_1_fu_87_ap_done),
    .ap_idle(grp_generic_fmod_double_Pipeline_1_fu_87_ap_idle),
    .ap_ready(grp_generic_fmod_double_Pipeline_1_fu_87_ap_ready),
    .zext_ln254(n_reg_361),
    .zext_ln300(ap_mx_reg_356),
    .r_sh_1_out(grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out),
    .r_sh_1_out_ap_vld(grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out_ap_vld)
);

dIFFT_ctlz_54_54_1_1 #(
    .din_WIDTH( 54 ),
    .dout_WIDTH( 54 ))
ctlz_54_54_1_1_U4(
    .din(grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out),
    .dout(tmp_5_fu_211_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_return_preg <= bitcast_ln497_fu_311_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_generic_fmod_double_Pipeline_1_fu_87_ap_start_reg <= 1'b0;
    end else begin
        if (((or_ln271_fu_153_p2 == 1'd1) & (or_ln267_fu_141_p2 == 1'd1) & (isyBx_e_fu_123_p2 == 1'd0) & (isF_e_x_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_generic_fmod_double_Pipeline_1_fu_87_ap_start_reg <= 1'b1;
        end else if ((grp_generic_fmod_double_Pipeline_1_fu_87_ap_ready == 1'b1)) begin
            grp_generic_fmod_double_Pipeline_1_fu_87_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((isyBx_e_fu_123_p2 == 1'd1) & (isF_e_x_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        retval_1_in_reg_70 <= ret_5_fu_101_p1;
    end else if (((icmp_ln319_fu_205_p2 == 1'd0) & (or_ln271_reg_352 == 1'd1) & (or_ln267_reg_348 == 1'd1) & (isyBx_e_reg_344 == 1'd0) & (isF_e_x_reg_340 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        retval_1_in_reg_70 <= t_5_fu_291_p4;
    end else if (((icmp_ln319_fu_205_p2 == 1'd1) & (or_ln271_reg_352 == 1'd1) & (or_ln267_reg_348 == 1'd1) & (isyBx_e_reg_344 == 1'd0) & (isF_e_x_reg_340 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        retval_1_in_reg_70 <= t_4_fu_302_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        retval_1_in_reg_70 <= t_3_fu_194_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        retval_1_in_reg_70 <= t_2_fu_185_p4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        retval_1_in_reg_70 <= t_fu_315_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ap_mx_reg_356[51 : 0] <= ap_mx_fu_169_p3[51 : 0];
        fz_sig_reg_335 <= fz_sig_fu_113_p1;
        isF_e_x_reg_340 <= isF_e_x_fu_117_p2;
        isyBx_e_reg_344 <= isyBx_e_fu_123_p2;
        n_reg_361 <= n_fu_178_p2;
        or_ln267_reg_348 <= or_ln267_fu_141_p2;
        or_ln271_reg_352 <= or_ln271_fu_153_p2;
        ret_5_reg_329 <= ret_5_fu_101_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_generic_fmod_double_Pipeline_1_fu_87_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_125)) begin
        if ((icmp_ln319_fu_205_p2 == 1'd0)) begin
            ap_phi_mux_retval_1_in_phi_fu_73_p12 = t_5_fu_291_p4;
        end else if ((icmp_ln319_fu_205_p2 == 1'd1)) begin
            ap_phi_mux_retval_1_in_phi_fu_73_p12 = t_4_fu_302_p3;
        end else begin
            ap_phi_mux_retval_1_in_phi_fu_73_p12 = retval_1_in_reg_70;
        end
    end else begin
        ap_phi_mux_retval_1_in_phi_fu_73_p12 = retval_1_in_reg_70;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_return = bitcast_ln497_fu_311_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((or_ln271_fu_153_p2 == 1'd1) & (or_ln267_fu_141_p2 == 1'd1) & (isyBx_e_fu_123_p2 == 1'd0) & (isF_e_x_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((or_ln271_fu_153_p2 == 1'd0) & (or_ln267_fu_141_p2 == 1'd1) & (isyBx_e_fu_123_p2 == 1'd0) & (isF_e_x_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((or_ln267_fu_141_p2 == 1'd0) & (isyBx_e_fu_123_p2 == 1'd0) & (isF_e_x_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((isyBx_e_fu_123_p2 == 1'd1) & (isF_e_x_fu_117_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((isF_e_x_fu_117_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_generic_fmod_double_Pipeline_1_fu_87_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln325_fu_227_p2 = ($signed(trunc_ln324_1_fu_223_p1) + $signed(7'd127));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_condition_125 = ((or_ln271_reg_352 == 1'd1) & (or_ln267_reg_348 == 1'd1) & (isyBx_e_reg_344 == 1'd0) & (isF_e_x_reg_340 == 1'd0) & (1'b1 == ap_CS_fsm_state5));
end

assign ap_mx_2_fu_267_p3 = ((icmp_ln325_fu_233_p2[0:0] == 1'b1) ? trunc_ln325_1_fu_239_p4 : empty_fu_263_p1);

assign ap_mx_fu_169_p3 = {{1'd1}, {fz_sig_fu_113_p1}};

assign bitcast_ln497_fu_311_p1 = ap_phi_mux_retval_1_in_phi_fu_73_p12;

assign empty_fu_263_p1 = shl_ln325_fu_257_p2[51:0];

assign fz_exp_1_fu_285_p2 = ($signed(sext_ln327_fu_281_p1) + $signed(11'd1023));

assign fz_exp_cast_fu_159_p4 = {{ret_5_fu_101_p1[61:52]}};

assign fz_exp_fu_105_p3 = {{ret_5_fu_101_p1[62:52]}};

assign fz_sig_fu_113_p1 = ret_5_fu_101_p1[51:0];

assign grp_fu_94_p3 = ret_5_reg_329[32'd63];

assign grp_generic_fmod_double_Pipeline_1_fu_87_ap_start = grp_generic_fmod_double_Pipeline_1_fu_87_ap_start_reg;

assign icmp_ln267_1_fu_135_p2 = ((fz_sig_fu_113_p1 > 52'd2567051787601182) ? 1'b1 : 1'b0);

assign icmp_ln267_fu_129_p2 = ((fz_exp_fu_105_p3 != 11'd1025) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_147_p2 = ((fz_sig_fu_113_p1 != 52'd2567051787601183) ? 1'b1 : 1'b0);

assign icmp_ln319_fu_205_p2 = ((grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out == 54'd0) ? 1'b1 : 1'b0);

assign icmp_ln325_fu_233_p2 = ((trunc_ln324_fu_219_p1 == 6'd0) ? 1'b1 : 1'b0);

assign isF_e_x_fu_117_p2 = ((fz_exp_fu_105_p3 == 11'd2047) ? 1'b1 : 1'b0);

assign isyBx_e_fu_123_p2 = ((fz_exp_fu_105_p3 < 11'd1025) ? 1'b1 : 1'b0);

assign n_fu_178_p2 = ($signed(fz_exp_cast_fu_159_p4) + $signed(10'd1023));

assign or_ln267_fu_141_p2 = (icmp_ln267_fu_129_p2 | icmp_ln267_1_fu_135_p2);

assign or_ln271_fu_153_p2 = (icmp_ln271_fu_147_p2 | icmp_ln267_fu_129_p2);

assign ret_5_fu_101_p1 = x;

assign sext_ln325_fu_249_p1 = $signed(add_ln325_fu_227_p2);

assign sext_ln327_fu_281_p1 = $signed(sub_ln327_fu_275_p2);

assign shl_ln325_fu_257_p2 = grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out << zext_ln325_fu_253_p1;

assign sub_ln327_fu_275_p2 = (7'd3 - trunc_ln324_1_fu_223_p1);

assign t_2_fu_185_p4 = {{{grp_fu_94_p3}, {11'd1025}}, {fz_sig_reg_335}};

assign t_3_fu_194_p3 = {{grp_fu_94_p3}, {63'd0}};

assign t_4_fu_302_p3 = {{grp_fu_94_p3}, {63'd0}};

assign t_5_fu_291_p4 = {{{grp_fu_94_p3}, {fz_exp_1_fu_285_p2}}, {ap_mx_2_fu_267_p3}};

assign t_fu_315_p3 = {{grp_fu_94_p3}, {63'd9223372036854775807}};

assign trunc_ln324_1_fu_223_p1 = tmp_5_fu_211_p3[6:0];

assign trunc_ln324_fu_219_p1 = tmp_5_fu_211_p3[5:0];

assign trunc_ln325_1_fu_239_p4 = {{grp_generic_fmod_double_Pipeline_1_fu_87_r_sh_1_out[52:1]}};

assign zext_ln325_fu_253_p1 = $unsigned(sext_ln325_fu_249_p1);

always @ (posedge ap_clk) begin
    ap_mx_reg_356[52] <= 1'b1;
end

endmodule //dIFFT_generic_fmod_double_s
