// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pFFT_pAccumulateFC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        k,
        p_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] k;
input  [39:0] p_read;
output  [0:0] ap_return_0;
output  [0:0] ap_return_1;
output  [5:0] ap_return_2;
output  [0:0] ap_return_3;
output  [29:0] ap_return_4;
output  [0:0] ap_return_5;
output  [0:0] ap_return_6;
output  [5:0] ap_return_7;
output  [0:0] ap_return_8;
output  [29:0] ap_return_9;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_fu_177_p2;
reg   [63:0] reg_186;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state16;
wire   [63:0] grp_fu_183_p1;
reg   [63:0] conv_reg_430;
wire    ap_CS_fsm_state4;
reg   [0:0] deltaTheta_sign_reg_435;
wire    ap_CS_fsm_state18;
reg   [0:0] deltaTheta_isZero_reg_440;
reg   [5:0] deltaTheta_regime_reg_445;
reg   [29:0] deltaTheta_mantissa_reg_450;
wire   [0:0] empty_fu_217_p1;
reg   [0:0] empty_reg_455;
reg   [0:0] tmp_reg_460;
reg   [29:0] x_mantissa_6_reg_465;
wire   [6:0] add_i321_i_fu_268_p2;
reg   [6:0] add_i321_i_reg_470;
wire    grp_double2posit_fu_120_ap_start;
wire    grp_double2posit_fu_120_ap_done;
wire    grp_double2posit_fu_120_ap_idle;
wire    grp_double2posit_fu_120_ap_ready;
wire   [0:0] grp_double2posit_fu_120_ap_return_0;
wire   [0:0] grp_double2posit_fu_120_ap_return_1;
wire   [5:0] grp_double2posit_fu_120_ap_return_2;
wire   [29:0] grp_double2posit_fu_120_ap_return_3;
wire   [63:0] grp_double2posit_fu_120_grp_fu_177_p_din0;
wire   [63:0] grp_double2posit_fu_120_grp_fu_177_p_din1;
wire    grp_double2posit_fu_120_grp_fu_177_p_ce;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_done;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_idle;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_ready;
wire   [29:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_mantissa_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_mantissa_write_assign_out_ap_vld;
wire   [0:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_exponent_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_exponent_write_assign_out_ap_vld;
wire   [5:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_regime_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_regime_write_assign_out_ap_vld;
wire   [0:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_isZero_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_isZero_write_assign_out_ap_vld;
wire   [0:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_sign_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_sign_write_assign_out_ap_vld;
wire   [29:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_mantissa_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_mantissa_write_assign_out_ap_vld;
wire   [0:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_exponent_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_exponent_write_assign_out_ap_vld;
wire   [5:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_regime_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_regime_write_assign_out_ap_vld;
wire   [0:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_isZero_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_isZero_write_assign_out_ap_vld;
wire   [0:0] grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_sign_write_assign_out;
wire    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_sign_write_assign_out_ap_vld;
reg    grp_double2posit_fu_120_ap_start_reg;
wire    ap_CS_fsm_state17;
reg    grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg   [63:0] grp_fu_177_p0;
reg   [63:0] grp_fu_177_p1;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
wire   [31:0] grp_fu_183_p0;
wire   [5:0] x_regime_fu_231_p4;
wire   [0:0] tmp_59_fu_256_p3;
wire  signed [6:0] conv_i337_i_fu_252_p1;
wire   [6:0] conv3_i13_i315_i_fu_264_p1;
reg    grp_fu_177_ce;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_double2posit_fu_120_ap_start_reg = 1'b0;
#0 grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start_reg = 1'b0;
end

pFFT_double2posit grp_double2posit_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_double2posit_fu_120_ap_start),
    .ap_done(grp_double2posit_fu_120_ap_done),
    .ap_idle(grp_double2posit_fu_120_ap_idle),
    .ap_ready(grp_double2posit_fu_120_ap_ready),
    .div(reg_186),
    .ap_return_0(grp_double2posit_fu_120_ap_return_0),
    .ap_return_1(grp_double2posit_fu_120_ap_return_1),
    .ap_return_2(grp_double2posit_fu_120_ap_return_2),
    .ap_return_3(grp_double2posit_fu_120_ap_return_3),
    .grp_fu_177_p_din0(grp_double2posit_fu_120_grp_fu_177_p_din0),
    .grp_fu_177_p_din1(grp_double2posit_fu_120_grp_fu_177_p_din1),
    .grp_fu_177_p_dout0(grp_fu_177_p2),
    .grp_fu_177_p_ce(grp_double2posit_fu_120_grp_fu_177_p_ce)
);

pFFT_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1 grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start),
    .ap_done(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_done),
    .ap_idle(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_idle),
    .ap_ready(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_ready),
    .empty_5(empty_reg_455),
    .empty(tmp_reg_460),
    .add_i321_i(add_i321_i_reg_470),
    .conv3_i_i351_i(x_mantissa_6_reg_465),
    .deltaTheta_sign(deltaTheta_sign_reg_435),
    .deltaTheta_isZero(deltaTheta_isZero_reg_440),
    .deltaTheta_regime(deltaTheta_regime_reg_445),
    .deltaTheta_mantissa(deltaTheta_mantissa_reg_450),
    .imagSum_mantissa_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_mantissa_write_assign_out),
    .imagSum_mantissa_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_mantissa_write_assign_out_ap_vld),
    .imagSum_exponent_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_exponent_write_assign_out),
    .imagSum_exponent_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_exponent_write_assign_out_ap_vld),
    .imagSum_regime_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_regime_write_assign_out),
    .imagSum_regime_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_regime_write_assign_out_ap_vld),
    .imagSum_isZero_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_isZero_write_assign_out),
    .imagSum_isZero_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_isZero_write_assign_out_ap_vld),
    .imagSum_sign_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_sign_write_assign_out),
    .imagSum_sign_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_sign_write_assign_out_ap_vld),
    .realSum_mantissa_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_mantissa_write_assign_out),
    .realSum_mantissa_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_mantissa_write_assign_out_ap_vld),
    .realSum_exponent_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_exponent_write_assign_out),
    .realSum_exponent_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_exponent_write_assign_out_ap_vld),
    .realSum_regime_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_regime_write_assign_out),
    .realSum_regime_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_regime_write_assign_out_ap_vld),
    .realSum_isZero_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_isZero_write_assign_out),
    .realSum_isZero_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_isZero_write_assign_out_ap_vld),
    .realSum_sign_write_assign_out(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_sign_write_assign_out),
    .realSum_sign_write_assign_out_ap_vld(grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_sign_write_assign_out_ap_vld)
);

pFFT_dmul_64ns_64ns_64_6_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_6_max_dsp_1_U135(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_177_p0),
    .din1(grp_fu_177_p1),
    .ce(grp_fu_177_ce),
    .dout(grp_fu_177_p2)
);

pFFT_sitodp_32ns_64_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_4_no_dsp_1_U136(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_183_p0),
    .ce(1'b1),
    .dout(grp_fu_183_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_double2posit_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_double2posit_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_double2posit_fu_120_ap_ready == 1'b1)) begin
            grp_double2posit_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_double2posit_fu_120_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
            grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start_reg <= 1'b1;
        end else if ((grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_ready == 1'b1)) begin
            grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        add_i321_i_reg_470 <= add_i321_i_fu_268_p2;
        deltaTheta_isZero_reg_440 <= grp_double2posit_fu_120_ap_return_1;
        deltaTheta_mantissa_reg_450 <= grp_double2posit_fu_120_ap_return_3;
        deltaTheta_regime_reg_445 <= grp_double2posit_fu_120_ap_return_2;
        deltaTheta_sign_reg_435 <= grp_double2posit_fu_120_ap_return_0;
        empty_reg_455 <= empty_fu_217_p1;
        tmp_reg_460 <= p_read[32'd1];
        x_mantissa_6_reg_465 <= {{p_read[39:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_reg_430 <= grp_fu_183_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_186 <= grp_fu_177_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_double2posit_fu_120_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_177_ce = grp_double2posit_fu_120_grp_fu_177_p_ce;
    end else begin
        grp_fu_177_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_177_p0 = grp_double2posit_fu_120_grp_fu_177_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_177_p0 = reg_186;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_177_p0 = conv_reg_430;
    end else begin
        grp_fu_177_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_177_p1 = grp_double2posit_fu_120_grp_fu_177_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_177_p1 = 64'd4580160821035794432;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_177_p1 = 64'd13842132293034192152;
    end else begin
        grp_fu_177_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_double2posit_fu_120_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i321_i_fu_268_p2 = ($signed(conv_i337_i_fu_252_p1) + $signed(conv3_i13_i315_i_fu_264_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return_0 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_sign_write_assign_out;

assign ap_return_1 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_isZero_write_assign_out;

assign ap_return_2 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_regime_write_assign_out;

assign ap_return_3 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_exponent_write_assign_out;

assign ap_return_4 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_realSum_mantissa_write_assign_out;

assign ap_return_5 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_sign_write_assign_out;

assign ap_return_6 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_isZero_write_assign_out;

assign ap_return_7 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_regime_write_assign_out;

assign ap_return_8 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_exponent_write_assign_out;

assign ap_return_9 = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_imagSum_mantissa_write_assign_out;

assign conv3_i13_i315_i_fu_264_p1 = tmp_59_fu_256_p3;

assign conv_i337_i_fu_252_p1 = $signed(x_regime_fu_231_p4);

assign empty_fu_217_p1 = p_read[0:0];

assign grp_double2posit_fu_120_ap_start = grp_double2posit_fu_120_ap_start_reg;

assign grp_fu_183_p0 = k;

assign grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start = grp_pAccumulateFC_Pipeline_VITIS_LOOP_1345_1_fu_155_ap_start_reg;

assign tmp_59_fu_256_p3 = p_read[32'd9];

assign x_regime_fu_231_p4 = {{p_read[8:3]}};

endmodule //pFFT_pAccumulateFC
