-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
-- 67d7842dbbe25473c3c32b93c0da8047785f30d78e8a024de1b57352245f9689

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pFFT_bitselect_1ns_154ns_32ns_1_1_1 is
generic (
    ADDRWIDTH : INTEGER := 32;
    DATAWIDTH : INTEGER := 154
);
port (

    sel   : in std_logic_vector (ADDRWIDTH-1 downto 0);
    din   : in std_logic_vector (DATAWIDTH-1 downto 0);
    dout  : out std_logic_vector (0 downto 0)
);
end entity;

architecture behav of pFFT_bitselect_1ns_154ns_32ns_1_1_1 is
    signal dout_tmp : std_logic_vector (0 downto 0);


begin

    process(din,sel) is
    begin
        case sel is
            
            when std_logic_vector(to_unsigned(0,sel'length)) =>
                dout_tmp(0) <= din(0);
            
            when std_logic_vector(to_unsigned(1,sel'length)) =>
                dout_tmp(0) <= din(1);
            
            when std_logic_vector(to_unsigned(2,sel'length)) =>
                dout_tmp(0) <= din(2);
            
            when std_logic_vector(to_unsigned(3,sel'length)) =>
                dout_tmp(0) <= din(3);
            
            when std_logic_vector(to_unsigned(4,sel'length)) =>
                dout_tmp(0) <= din(4);
            
            when std_logic_vector(to_unsigned(5,sel'length)) =>
                dout_tmp(0) <= din(5);
            
            when std_logic_vector(to_unsigned(6,sel'length)) =>
                dout_tmp(0) <= din(6);
            
            when std_logic_vector(to_unsigned(7,sel'length)) =>
                dout_tmp(0) <= din(7);
            
            when std_logic_vector(to_unsigned(8,sel'length)) =>
                dout_tmp(0) <= din(8);
            
            when std_logic_vector(to_unsigned(9,sel'length)) =>
                dout_tmp(0) <= din(9);
            
            when std_logic_vector(to_unsigned(10,sel'length)) =>
                dout_tmp(0) <= din(10);
            
            when std_logic_vector(to_unsigned(11,sel'length)) =>
                dout_tmp(0) <= din(11);
            
            when std_logic_vector(to_unsigned(12,sel'length)) =>
                dout_tmp(0) <= din(12);
            
            when std_logic_vector(to_unsigned(13,sel'length)) =>
                dout_tmp(0) <= din(13);
            
            when std_logic_vector(to_unsigned(14,sel'length)) =>
                dout_tmp(0) <= din(14);
            
            when std_logic_vector(to_unsigned(15,sel'length)) =>
                dout_tmp(0) <= din(15);
            
            when std_logic_vector(to_unsigned(16,sel'length)) =>
                dout_tmp(0) <= din(16);
            
            when std_logic_vector(to_unsigned(17,sel'length)) =>
                dout_tmp(0) <= din(17);
            
            when std_logic_vector(to_unsigned(18,sel'length)) =>
                dout_tmp(0) <= din(18);
            
            when std_logic_vector(to_unsigned(19,sel'length)) =>
                dout_tmp(0) <= din(19);
            
            when std_logic_vector(to_unsigned(20,sel'length)) =>
                dout_tmp(0) <= din(20);
            
            when std_logic_vector(to_unsigned(21,sel'length)) =>
                dout_tmp(0) <= din(21);
            
            when std_logic_vector(to_unsigned(22,sel'length)) =>
                dout_tmp(0) <= din(22);
            
            when std_logic_vector(to_unsigned(23,sel'length)) =>
                dout_tmp(0) <= din(23);
            
            when std_logic_vector(to_unsigned(24,sel'length)) =>
                dout_tmp(0) <= din(24);
            
            when std_logic_vector(to_unsigned(25,sel'length)) =>
                dout_tmp(0) <= din(25);
            
            when std_logic_vector(to_unsigned(26,sel'length)) =>
                dout_tmp(0) <= din(26);
            
            when std_logic_vector(to_unsigned(27,sel'length)) =>
                dout_tmp(0) <= din(27);
            
            when std_logic_vector(to_unsigned(28,sel'length)) =>
                dout_tmp(0) <= din(28);
            
            when std_logic_vector(to_unsigned(29,sel'length)) =>
                dout_tmp(0) <= din(29);
            
            when std_logic_vector(to_unsigned(30,sel'length)) =>
                dout_tmp(0) <= din(30);
            
            when std_logic_vector(to_unsigned(31,sel'length)) =>
                dout_tmp(0) <= din(31);
            
            when std_logic_vector(to_unsigned(32,sel'length)) =>
                dout_tmp(0) <= din(32);
            
            when std_logic_vector(to_unsigned(33,sel'length)) =>
                dout_tmp(0) <= din(33);
            
            when std_logic_vector(to_unsigned(34,sel'length)) =>
                dout_tmp(0) <= din(34);
            
            when std_logic_vector(to_unsigned(35,sel'length)) =>
                dout_tmp(0) <= din(35);
            
            when std_logic_vector(to_unsigned(36,sel'length)) =>
                dout_tmp(0) <= din(36);
            
            when std_logic_vector(to_unsigned(37,sel'length)) =>
                dout_tmp(0) <= din(37);
            
            when std_logic_vector(to_unsigned(38,sel'length)) =>
                dout_tmp(0) <= din(38);
            
            when std_logic_vector(to_unsigned(39,sel'length)) =>
                dout_tmp(0) <= din(39);
            
            when std_logic_vector(to_unsigned(40,sel'length)) =>
                dout_tmp(0) <= din(40);
            
            when std_logic_vector(to_unsigned(41,sel'length)) =>
                dout_tmp(0) <= din(41);
            
            when std_logic_vector(to_unsigned(42,sel'length)) =>
                dout_tmp(0) <= din(42);
            
            when std_logic_vector(to_unsigned(43,sel'length)) =>
                dout_tmp(0) <= din(43);
            
            when std_logic_vector(to_unsigned(44,sel'length)) =>
                dout_tmp(0) <= din(44);
            
            when std_logic_vector(to_unsigned(45,sel'length)) =>
                dout_tmp(0) <= din(45);
            
            when std_logic_vector(to_unsigned(46,sel'length)) =>
                dout_tmp(0) <= din(46);
            
            when std_logic_vector(to_unsigned(47,sel'length)) =>
                dout_tmp(0) <= din(47);
            
            when std_logic_vector(to_unsigned(48,sel'length)) =>
                dout_tmp(0) <= din(48);
            
            when std_logic_vector(to_unsigned(49,sel'length)) =>
                dout_tmp(0) <= din(49);
            
            when std_logic_vector(to_unsigned(50,sel'length)) =>
                dout_tmp(0) <= din(50);
            
            when std_logic_vector(to_unsigned(51,sel'length)) =>
                dout_tmp(0) <= din(51);
            
            when std_logic_vector(to_unsigned(52,sel'length)) =>
                dout_tmp(0) <= din(52);
            
            when std_logic_vector(to_unsigned(53,sel'length)) =>
                dout_tmp(0) <= din(53);
            
            when std_logic_vector(to_unsigned(54,sel'length)) =>
                dout_tmp(0) <= din(54);
            
            when std_logic_vector(to_unsigned(55,sel'length)) =>
                dout_tmp(0) <= din(55);
            
            when std_logic_vector(to_unsigned(56,sel'length)) =>
                dout_tmp(0) <= din(56);
            
            when std_logic_vector(to_unsigned(57,sel'length)) =>
                dout_tmp(0) <= din(57);
            
            when std_logic_vector(to_unsigned(58,sel'length)) =>
                dout_tmp(0) <= din(58);
            
            when std_logic_vector(to_unsigned(59,sel'length)) =>
                dout_tmp(0) <= din(59);
            
            when std_logic_vector(to_unsigned(60,sel'length)) =>
                dout_tmp(0) <= din(60);
            
            when std_logic_vector(to_unsigned(61,sel'length)) =>
                dout_tmp(0) <= din(61);
            
            when std_logic_vector(to_unsigned(62,sel'length)) =>
                dout_tmp(0) <= din(62);
            
            when std_logic_vector(to_unsigned(63,sel'length)) =>
                dout_tmp(0) <= din(63);
            
            when std_logic_vector(to_unsigned(64,sel'length)) =>
                dout_tmp(0) <= din(64);
            
            when std_logic_vector(to_unsigned(65,sel'length)) =>
                dout_tmp(0) <= din(65);
            
            when std_logic_vector(to_unsigned(66,sel'length)) =>
                dout_tmp(0) <= din(66);
            
            when std_logic_vector(to_unsigned(67,sel'length)) =>
                dout_tmp(0) <= din(67);
            
            when std_logic_vector(to_unsigned(68,sel'length)) =>
                dout_tmp(0) <= din(68);
            
            when std_logic_vector(to_unsigned(69,sel'length)) =>
                dout_tmp(0) <= din(69);
            
            when std_logic_vector(to_unsigned(70,sel'length)) =>
                dout_tmp(0) <= din(70);
            
            when std_logic_vector(to_unsigned(71,sel'length)) =>
                dout_tmp(0) <= din(71);
            
            when std_logic_vector(to_unsigned(72,sel'length)) =>
                dout_tmp(0) <= din(72);
            
            when std_logic_vector(to_unsigned(73,sel'length)) =>
                dout_tmp(0) <= din(73);
            
            when std_logic_vector(to_unsigned(74,sel'length)) =>
                dout_tmp(0) <= din(74);
            
            when std_logic_vector(to_unsigned(75,sel'length)) =>
                dout_tmp(0) <= din(75);
            
            when std_logic_vector(to_unsigned(76,sel'length)) =>
                dout_tmp(0) <= din(76);
            
            when std_logic_vector(to_unsigned(77,sel'length)) =>
                dout_tmp(0) <= din(77);
            
            when std_logic_vector(to_unsigned(78,sel'length)) =>
                dout_tmp(0) <= din(78);
            
            when std_logic_vector(to_unsigned(79,sel'length)) =>
                dout_tmp(0) <= din(79);
            
            when std_logic_vector(to_unsigned(80,sel'length)) =>
                dout_tmp(0) <= din(80);
            
            when std_logic_vector(to_unsigned(81,sel'length)) =>
                dout_tmp(0) <= din(81);
            
            when std_logic_vector(to_unsigned(82,sel'length)) =>
                dout_tmp(0) <= din(82);
            
            when std_logic_vector(to_unsigned(83,sel'length)) =>
                dout_tmp(0) <= din(83);
            
            when std_logic_vector(to_unsigned(84,sel'length)) =>
                dout_tmp(0) <= din(84);
            
            when std_logic_vector(to_unsigned(85,sel'length)) =>
                dout_tmp(0) <= din(85);
            
            when std_logic_vector(to_unsigned(86,sel'length)) =>
                dout_tmp(0) <= din(86);
            
            when std_logic_vector(to_unsigned(87,sel'length)) =>
                dout_tmp(0) <= din(87);
            
            when std_logic_vector(to_unsigned(88,sel'length)) =>
                dout_tmp(0) <= din(88);
            
            when std_logic_vector(to_unsigned(89,sel'length)) =>
                dout_tmp(0) <= din(89);
            
            when std_logic_vector(to_unsigned(90,sel'length)) =>
                dout_tmp(0) <= din(90);
            
            when std_logic_vector(to_unsigned(91,sel'length)) =>
                dout_tmp(0) <= din(91);
            
            when std_logic_vector(to_unsigned(92,sel'length)) =>
                dout_tmp(0) <= din(92);
            
            when std_logic_vector(to_unsigned(93,sel'length)) =>
                dout_tmp(0) <= din(93);
            
            when std_logic_vector(to_unsigned(94,sel'length)) =>
                dout_tmp(0) <= din(94);
            
            when std_logic_vector(to_unsigned(95,sel'length)) =>
                dout_tmp(0) <= din(95);
            
            when std_logic_vector(to_unsigned(96,sel'length)) =>
                dout_tmp(0) <= din(96);
            
            when std_logic_vector(to_unsigned(97,sel'length)) =>
                dout_tmp(0) <= din(97);
            
            when std_logic_vector(to_unsigned(98,sel'length)) =>
                dout_tmp(0) <= din(98);
            
            when std_logic_vector(to_unsigned(99,sel'length)) =>
                dout_tmp(0) <= din(99);
            
            when std_logic_vector(to_unsigned(100,sel'length)) =>
                dout_tmp(0) <= din(100);
            
            when std_logic_vector(to_unsigned(101,sel'length)) =>
                dout_tmp(0) <= din(101);
            
            when std_logic_vector(to_unsigned(102,sel'length)) =>
                dout_tmp(0) <= din(102);
            
            when std_logic_vector(to_unsigned(103,sel'length)) =>
                dout_tmp(0) <= din(103);
            
            when std_logic_vector(to_unsigned(104,sel'length)) =>
                dout_tmp(0) <= din(104);
            
            when std_logic_vector(to_unsigned(105,sel'length)) =>
                dout_tmp(0) <= din(105);
            
            when std_logic_vector(to_unsigned(106,sel'length)) =>
                dout_tmp(0) <= din(106);
            
            when std_logic_vector(to_unsigned(107,sel'length)) =>
                dout_tmp(0) <= din(107);
            
            when std_logic_vector(to_unsigned(108,sel'length)) =>
                dout_tmp(0) <= din(108);
            
            when std_logic_vector(to_unsigned(109,sel'length)) =>
                dout_tmp(0) <= din(109);
            
            when std_logic_vector(to_unsigned(110,sel'length)) =>
                dout_tmp(0) <= din(110);
            
            when std_logic_vector(to_unsigned(111,sel'length)) =>
                dout_tmp(0) <= din(111);
            
            when std_logic_vector(to_unsigned(112,sel'length)) =>
                dout_tmp(0) <= din(112);
            
            when std_logic_vector(to_unsigned(113,sel'length)) =>
                dout_tmp(0) <= din(113);
            
            when std_logic_vector(to_unsigned(114,sel'length)) =>
                dout_tmp(0) <= din(114);
            
            when std_logic_vector(to_unsigned(115,sel'length)) =>
                dout_tmp(0) <= din(115);
            
            when std_logic_vector(to_unsigned(116,sel'length)) =>
                dout_tmp(0) <= din(116);
            
            when std_logic_vector(to_unsigned(117,sel'length)) =>
                dout_tmp(0) <= din(117);
            
            when std_logic_vector(to_unsigned(118,sel'length)) =>
                dout_tmp(0) <= din(118);
            
            when std_logic_vector(to_unsigned(119,sel'length)) =>
                dout_tmp(0) <= din(119);
            
            when std_logic_vector(to_unsigned(120,sel'length)) =>
                dout_tmp(0) <= din(120);
            
            when std_logic_vector(to_unsigned(121,sel'length)) =>
                dout_tmp(0) <= din(121);
            
            when std_logic_vector(to_unsigned(122,sel'length)) =>
                dout_tmp(0) <= din(122);
            
            when std_logic_vector(to_unsigned(123,sel'length)) =>
                dout_tmp(0) <= din(123);
            
            when std_logic_vector(to_unsigned(124,sel'length)) =>
                dout_tmp(0) <= din(124);
            
            when std_logic_vector(to_unsigned(125,sel'length)) =>
                dout_tmp(0) <= din(125);
            
            when std_logic_vector(to_unsigned(126,sel'length)) =>
                dout_tmp(0) <= din(126);
            
            when std_logic_vector(to_unsigned(127,sel'length)) =>
                dout_tmp(0) <= din(127);
            
            when std_logic_vector(to_unsigned(128,sel'length)) =>
                dout_tmp(0) <= din(128);
            
            when std_logic_vector(to_unsigned(129,sel'length)) =>
                dout_tmp(0) <= din(129);
            
            when std_logic_vector(to_unsigned(130,sel'length)) =>
                dout_tmp(0) <= din(130);
            
            when std_logic_vector(to_unsigned(131,sel'length)) =>
                dout_tmp(0) <= din(131);
            
            when std_logic_vector(to_unsigned(132,sel'length)) =>
                dout_tmp(0) <= din(132);
            
            when std_logic_vector(to_unsigned(133,sel'length)) =>
                dout_tmp(0) <= din(133);
            
            when std_logic_vector(to_unsigned(134,sel'length)) =>
                dout_tmp(0) <= din(134);
            
            when std_logic_vector(to_unsigned(135,sel'length)) =>
                dout_tmp(0) <= din(135);
            
            when std_logic_vector(to_unsigned(136,sel'length)) =>
                dout_tmp(0) <= din(136);
            
            when std_logic_vector(to_unsigned(137,sel'length)) =>
                dout_tmp(0) <= din(137);
            
            when std_logic_vector(to_unsigned(138,sel'length)) =>
                dout_tmp(0) <= din(138);
            
            when std_logic_vector(to_unsigned(139,sel'length)) =>
                dout_tmp(0) <= din(139);
            
            when std_logic_vector(to_unsigned(140,sel'length)) =>
                dout_tmp(0) <= din(140);
            
            when std_logic_vector(to_unsigned(141,sel'length)) =>
                dout_tmp(0) <= din(141);
            
            when std_logic_vector(to_unsigned(142,sel'length)) =>
                dout_tmp(0) <= din(142);
            
            when std_logic_vector(to_unsigned(143,sel'length)) =>
                dout_tmp(0) <= din(143);
            
            when std_logic_vector(to_unsigned(144,sel'length)) =>
                dout_tmp(0) <= din(144);
            
            when std_logic_vector(to_unsigned(145,sel'length)) =>
                dout_tmp(0) <= din(145);
            
            when std_logic_vector(to_unsigned(146,sel'length)) =>
                dout_tmp(0) <= din(146);
            
            when std_logic_vector(to_unsigned(147,sel'length)) =>
                dout_tmp(0) <= din(147);
            
            when std_logic_vector(to_unsigned(148,sel'length)) =>
                dout_tmp(0) <= din(148);
            
            when std_logic_vector(to_unsigned(149,sel'length)) =>
                dout_tmp(0) <= din(149);
            
            when std_logic_vector(to_unsigned(150,sel'length)) =>
                dout_tmp(0) <= din(150);
            
            when std_logic_vector(to_unsigned(151,sel'length)) =>
                dout_tmp(0) <= din(151);
            
            when std_logic_vector(to_unsigned(152,sel'length)) =>
                dout_tmp(0) <= din(152);
            
            when std_logic_vector(to_unsigned(153,sel'length)) =>
                dout_tmp(0) <= din(153);
            
            when others => 
                dout_tmp(0) <= 'X';
        end case;
    end process;


    dout <= dout_tmp;




end architecture;
